//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMSearchBarDisplayController.h"

#import "ContactInfoViewControllerDelegate.h"
#import "ContactsItemViewDelegate.h"
#import "IAddressBookFriendMgrExt.h"
#import "SendVerifyMsgViewControllerDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "VerifyPhoneDelegate.h"
#import "contactInfoDelegate.h"
#import "contactVerifyLogicDelegate.h"

@class AddressBookFriend, CContactVerifyLogic, ContactInfoViewController, MMTableView, NSMutableArray, NSMutableDictionary, NSString, UIButton, UITextField;

@interface AddressBookFriendViewController : MMSearchBarDisplayController <UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate, IAddressBookFriendMgrExt, contactInfoDelegate, VerifyPhoneDelegate, ContactInfoViewControllerDelegate, ContactsItemViewDelegate, contactVerifyLogicDelegate, SendVerifyMsgViewControllerDelegate>
{
    MMTableView *m_tableView;
    UITextField *m_searchTextField;
    UIButton *m_searchBtn;
    AddressBookFriend *m_oCurrentFriendWrap;
    NSMutableArray *m_arrAddressBookFriendList;
    NSMutableDictionary *m_dicNicknameToFriends;
    NSMutableArray *m_arrFilteredFriendList;
    ContactInfoViewController *m_CurrentFriendItemView;
    CContactVerifyLogic *m_oContactVerifyLogic;
    NSMutableArray *m_arrKey;
    NSMutableDictionary *m_dicFriendList;
}

- (void).cxx_destruct;
- (void)addToContactsFromContactInfo:(id)arg1;
- (void)bindPhoneReturn;
- (_Bool)canSyncAddressBook;
- (void)contactVerifyOk:(id)arg1 opCode:(unsigned int)arg2;
- (void)dealloc;
- (void)doSearch:(id)arg1;
- (id)init;
- (void)initView;
- (void)loadData:(_Bool)arg1;
@property(retain, nonatomic) ContactInfoViewController *m_CurrentFriendItemView; // @synthesize m_CurrentFriendItemView;
@property(retain, nonatomic) AddressBookFriend *m_oCurrentFriendWrap; // @synthesize m_oCurrentFriendWrap;
- (void)makeAddressBookFriendCell:(id)arg1 row:(unsigned long long)arg2 section:(unsigned long long)arg3 tableView:(id)arg4;
- (void)newAddressBookFriendArrived;
- (void)newMessageFromContactInfo:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onAddContact;
- (void)onContactVerifyFail;
- (void)onContactVerifyFillVerifyMsg:(id)arg1;
- (void)onContactsItemViewRightButtonClick:(id)arg1;
- (void)onRemoveContact;
- (void)onSendVerifyMsgCancel;
- (void)onSendVerifyMsgOK;
- (void)onUpdateContact:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (void)sortFriendList;
- (void)startLoading;
- (void)stopLoading;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)trySyncAddressBook;
- (void)verifyContactWithOpCode:(id)arg1 opcode:(unsigned int)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

