//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMessageWrap, NSString;

@interface BrandSessionCache : NSObject
{
    _Bool hasNewArrival;
    NSString *latestMsgOwner;
    CMessageWrap *latestMsg;
}

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
@property(nonatomic) _Bool hasNewArrival; // @synthesize hasNewArrival;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) CMessageWrap *latestMsg; // @synthesize latestMsg;
@property(copy, nonatomic) NSString *latestMsgOwner; // @synthesize latestMsgOwner;

@end

