//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "AppUserInterfaceSizeDelegate.h"
#import "IMsgExt.h"
#import "IVoiceReminderExt.h"
#import "MMKernelExt.h"
#import "MMTabBarControllerDelegate.h"
#import "MMThemeManagerExt.h"
#import "UIAlertViewDelegate.h"
#import "UISplitViewControllerDelegate.h"
#import "UITabBarControllerDelegate.h"
#import "WCFacadeExt.h"
#import "WCPayThirdLaunchNotify.h"
#import "WCPayWalletLockVerifyLogicDelegate.h"

@class CMMVector, MMMainViewController, MMSplitViewController, MMTabBarController, NSMutableArray, NSString, PreEnterWechatLogic, SplitViewEmptyViewController, SvrErrorTipWindow, UIViewController, UIWindow;

@interface CAppViewControllerManager : MMObject <WCPayThirdLaunchNotify, MMTabBarControllerDelegate, WCPayWalletLockVerifyLogicDelegate, UISplitViewControllerDelegate, AppUserInterfaceSizeDelegate, UITabBarControllerDelegate, MMThemeManagerExt, MMKernelExt, IMsgExt, IVoiceReminderExt, WCFacadeExt, UIAlertViewDelegate>
{
    UIWindow *m_window;
    NSMutableArray *m_arrViewController;
    NSMutableArray *m_arrTabBarBaseViewController;
    unsigned int m_uCurrentTabViewIndex;
    CMMVector *m_vecViewController;
    _Bool m_bFromReg;
    _Bool m_isChangingTheme;
    SvrErrorTipWindow *m_svrErrorTipWindow;
    PreEnterWechatLogic *m_PreEnterWechatLogic;
    MMTabBarController *m_tabbarController;
    MMMainViewController *m_mainViewController;
    MMSplitViewController *m_splitViewController;
    SplitViewEmptyViewController *m_emptyVc;
    NSMutableArray *m_detailViewControllers;
    _Bool m_lastPush;
    _Bool _m_isHandlingOrientationEvent;
    _Bool _m_isForceUsingSingleColumnMode;
    NSMutableArray *_m_presentedViewControllers;
    UIViewController *_m_lastPresentedViewController;
}

+ (id)getAppViewControllerManager;
+ (id)getCurrentNavigationController;
+ (id)getTabBarController;
+ (_Bool)hasEnterWechatMain;
+ (id)topMostController;
+ (id)topViewControllerOfMainWindow;
+ (id)topViewControllerOfWindow:(id)arg1;
- (void).cxx_destruct;
- (void)HandleFindFriendJump:(id)arg1;
- (void)HandleMainFrameJump:(id)arg1;
- (void)HandleMoreJump:(id)arg1;
- (void)JumpToViewController:(id)arg1;
- (void)OnMainFrameDoubleClicked:(id)arg1;
- (void)OnShowPush:(id)arg1;
- (void)UIWindowDidBecomeHiddenNotification:(id)arg1;
- (void)UIWindowDidBecomeKeyNotification:(id)arg1;
- (void)UIWindowDidBecomeVisibleNotification:(id)arg1;
- (void)UIWindowDidResignKeyNotification:(id)arg1;
- (void)addViewController:(id)arg1;
- (void)addViewControllerToRootView:(id)arg1;
- (void)addViewToRootView:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)changeLanguage;
- (void)changeToSingleViewController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)changeToSplitViewController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)checkColumnModeForCurOrientationIfNeeded;
- (void)checkIfTopVCAnimatingAndToogleColumnMode;
- (_Bool)checkResentFailMsgForNotification:(id)arg1 isFromLaunch:(_Bool)arg2;
- (void)closeMainFrame;
- (void)createContactsViewController;
- (void)createFindFriendViewController;
- (void)createMainFrameWithShowStyle:(id)arg1;
- (void)createMoreViewController;
- (void)createNewMainFrameViewController;
- (void)createTabbarController;
- (void)dealloc;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)didTakeSnapshot:(id)arg1;
- (void)dismissAllPresentedViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dismissToRootViewController;
- (void)dismissToRootViewControllerForIndex:(long long)arg1;
- (void)endForceUsingSingleColumnMode;
- (id)findLastPresentedViewControllerWith:(id)arg1;
- (void)fixOnStatusBarClick;
- (void)forceRedrawNavigationBars;
- (void)forceUsingSingleColumnMode;
- (id)formatCGFloat:(double)arg1;
- (unsigned int)getCurTabBarIndex;
- (double)getLeftColumnWidthForSplitView;
- (id)getMMMainViewController;
- (id)getMMSplitViewController;
- (id)getMMTabBarController;
- (id)getMainWindow;
- (id)getNewMainFrameViewController;
- (id)getPreEnterWechatLogic;
- (id)getRightViewControllerForSplitView;
- (id)getSplitDetailNavigationController;
- (id)getSplitPresentedViewController;
- (id)getTabBarBaseViewController:(unsigned long long)arg1;
- (id)getTabBarController;
- (id)getTopViewController;
- (unsigned int)getTotalUnReadCount;
- (id)initWithWindow:(id)arg1;
- (void)internalChangeToSingleViewController:(id)arg1;
- (id)internalChangeToSplitViewController:(id)arg1;
- (_Bool)isChangingTheme;
- (_Bool)isInStatusBarShowViewController;
- (_Bool)isNowInRootViewController;
- (_Bool)isTopVCAnimating;
- (_Bool)isUsingSplitView;
- (void)jumpToAlbum;
- (void)jumpToCameraScan:(int)arg1;
- (void)jumpToCameraScan:(int)arg1 showMainView:(_Bool)arg2;
- (void)jumpToChat:(id)arg1 msgToLocate:(unsigned int)arg2;
- (void)jumpToOfflinePay;
- (void)jumpToSettingPrivacy:(_Bool)arg1;
- (void)jumpToSettingWcRecentPrivacy:(unsigned long long)arg1;
- (void)jumpToShake;
- (void)jumpToShareCard;
- (void)jumpToURLShardBy3rdApp:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
@property(nonatomic) _Bool m_isForceUsingSingleColumnMode; // @synthesize m_isForceUsingSingleColumnMode=_m_isForceUsingSingleColumnMode;
@property(nonatomic) _Bool m_isHandlingOrientationEvent; // @synthesize m_isHandlingOrientationEvent=_m_isHandlingOrientationEvent;
@property(retain, nonatomic) UIViewController *m_lastPresentedViewController; // @synthesize m_lastPresentedViewController=_m_lastPresentedViewController;
@property(retain, nonatomic) NSMutableArray *m_presentedViewControllers; // @synthesize m_presentedViewControllers=_m_presentedViewControllers;
- (void)moveToRootViewController;
- (void)moveToRootViewControllerForIndex:(long long)arg1;
- (void)moveToTab:(long long)arg1 showMainView:(_Bool)arg2;
- (void)newMessageByContact:(id)arg1 msgWrapToAdd:(id)arg2;
- (void)newMessageByContact:(id)arg1 msgWrapToAdd:(id)arg2 animated:(_Bool)arg3;
- (void)newMessageByContact:(id)arg1 msgWrapToAdd:(id)arg2 showMainView:(_Bool)arg3;
- (void)newMessageByContact:(id)arg1 msgWrapToAdd:(id)arg2 showMainView:(_Bool)arg3 animated:(_Bool)arg4;
- (void)newMessageByContact:(id)arg1 msgWrapToAdd:(id)arg2 showMainView:(_Bool)arg3 animated:(_Bool)arg4 extraInfo:(id)arg5;
- (void)newMessageByEnterpriseContact:(id)arg1 msgWrapToAdd:(id)arg2 showMainView:(_Bool)arg3 showSessionList:(_Bool)arg4 animated:(_Bool)arg5 extraInfo:(id)arg6;
- (id)notificationInfoForMessage:(id)arg1 withEnabledNotificationTypes:(unsigned long long)arg2;
- (void)onAppUserInterfaceSizeChanged:(id)arg1 previousTraitCollection:(id)arg2 currentTraitCollection:(id)arg3;
- (void)onDataChangedWithAdded:(id)arg1 andChanged:(id)arg2 andDeleted:(id)arg3;
- (void)onInterfaceSizeChangedToCompact;
- (void)onInterfaceSizeChangedToRegular;
- (void)onNotifyRemindMsg:(id)arg1;
- (void)onPreQuit;
- (void)onThemeChanged;
- (void)onWCPayThirdLaunchComplete;
- (void)onWCPayThirdLaunchEnd;
- (void)openFirstView;
- (void)openMainFrame:(_Bool)arg1 showStyle:(id)arg2;
- (void)openMainFrameFirstStep:(_Bool)arg1;
- (void)openPluginFeature:(int)arg1;
- (void)openView:(unsigned int)arg1 launchOptions:(id)arg2 isAppUpdated:(_Bool)arg3;
- (void)presentAllViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)printView:(id)arg1 withLevel:(int)arg2 buffer:(id)arg3;
- (void)reSendAllMsgFromNotificationDone;
- (void)recreateFindFriendViewController;
- (void)refreshLanguage:(int)arg1;
- (void)refreshLanguage:(int)arg1 withChildScene:(id)arg2;
- (void)refreshMainFrame;
- (void)removeViewController:(id)arg1;
- (void)removeViewFromRootView:(id)arg1;
- (void)removeViewFromRootViewController:(id)arg1;
- (void)replaceTwoFile:(id)arg1 desFile:(id)arg2;
- (void)resendAllFailMsgFromLocalNotification:(id)arg1;
- (void)resetNavItem:(id)arg1;
- (void)resetTabbarAndSplitView;
- (void)restartAllFailUploadFromLocalNotification;
- (void)setAllTabBarItemEnabled:(_Bool)arg1;
- (void)setPrimaryHidden;
- (void)setPrimaryShown;
- (void)setRightViewControllerForSplitView:(id)arg1 forPush:(_Bool)arg2;
- (_Bool)shouldChangeToOtherSplitMode:(id)arg1;
- (_Bool)shouldCreateSplitView;
- (_Bool)splitViewController:(id)arg1 shouldHideViewController:(id)arg2 inOrientation:(long long)arg3;
- (void)splitViewPopToRootViewController;
- (void)tabBarController:(id)arg1 didSelectViewController:(id)arg2;
- (_Bool)tabBarController:(id)arg1 shouldSelectViewController:(id)arg2;
- (void)toogleColumnModelIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)walletLockVerifySuccess:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

