//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WCMediaItem;

@interface CdnSnsTaskInfo : NSObject
{
    int m_nRetCode;
    unsigned long long m_ui64StartTime;
    unsigned int m_uiFileType;
    unsigned int m_uiFileSize;
    NSString *m_nsCdnStatInfo;
    WCMediaItem *m_oWCMediaItem;
    int downloadType;
    NSString *m_nsClientID;
}

- (void).cxx_destruct;
- (id)GetStatInfo;
@property(nonatomic) int downloadType; // @synthesize downloadType;
- (id)init;
@property(nonatomic) int m_nRetCode; // @synthesize m_nRetCode;
@property(retain, nonatomic) NSString *m_nsCdnStatInfo; // @synthesize m_nsCdnStatInfo;
@property(retain, nonatomic) NSString *m_nsClientID; // @synthesize m_nsClientID;
@property(retain, nonatomic) WCMediaItem *m_oWCMediaItem; // @synthesize m_oWCMediaItem;
@property(nonatomic) unsigned long long m_ui64StartTime; // @synthesize m_ui64StartTime;
@property(nonatomic) unsigned int m_uiFileSize; // @synthesize m_uiFileSize;
@property(nonatomic) unsigned int m_uiFileType; // @synthesize m_uiFileType;

@end

