//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseChatCellView.h"

#import "ChatBackgroundExt.h"

@class ChatTimeViewModel, MMTimer, UIImageView, UILabel;

@interface ChatTimeCellView : BaseChatCellView <ChatBackgroundExt>
{
    MMTimer *m_updateTimeLabelTimer;
    UILabel *m_timeLabel;
    UIImageView *m_bgImageView;
    _Bool _useLightStyle;
}

- (void).cxx_destruct;
- (_Bool)canBeReused;
- (void)dealloc;
- (id)initWithViewModel:(id)arg1;
- (void)layoutInternal;
- (_Bool)needUpdateLightStyle;
- (void)onChatBackgroundChanged:(id)arg1;
@property(nonatomic) _Bool useLightStyle; // @synthesize useLightStyle=_useLightStyle;
- (_Bool)shouldLayoutIfNeeded;

// Remaining properties
@property(readonly, nonatomic) ChatTimeViewModel *viewModel; // @dynamic viewModel;

@end

