//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CleanTaskInfo : NSObject
{
    unsigned int _readWriteInterval;
    NSString *_fileDirPath;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *fileDirPath; // @synthesize fileDirPath=_fileDirPath;
@property(nonatomic) unsigned int readWriteInterval; // @synthesize readWriteInterval=_readWriteInterval;

@end

