//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ContactInfoAssistDelegate.h"
#import "ForwardMessageLogicDelegate.h"
#import "ICertInfoMgrExt.h"
#import "IContactMgrExt.h"
#import "IHDHeadImageViewExt.h"
#import "IStrangerContactMgrExt.h"
#import "IUpdateProfileMgrExt.h"
#import "MMSayHelloViewControllerDelegate.h"
#import "PBMessageObserverDelegate.h"
#import "UIAlertViewDelegate.h"
#import "VerifyPhoneDelegate.h"
#import "WCFacadeExt.h"

@class CBaseContactInfoAssist, CContact, CContactVerifyLogic, CMessageWrap, ForwardMessageLogicController, NSMutableDictionary, NSString;

@interface ContactInfoViewController : MMUIViewController <ForwardMessageLogicDelegate, UIAlertViewDelegate, PBMessageObserverDelegate, ContactInfoAssistDelegate, IContactMgrExt, VerifyPhoneDelegate, MMSayHelloViewControllerDelegate, ICertInfoMgrExt, WCFacadeExt, IStrangerContactMgrExt, IUpdateProfileMgrExt, IHDHeadImageViewExt>
{
    unsigned int m_uiVerify;
    CContact *m_contact;
    CContact *m_chatContact;
    id <contactInfoDelegate> m_delegate;
    id <ContactInfoViewControllerDelegate> m_InfoDelegate;
    CBaseContactInfoAssist *m_oContactInfoAssist;
    CContactVerifyLogic *m_contactVerifyLogic;
    NSString *m_nsLocation;
    _Bool m_bPopToRootWhenDelete;
    unsigned int m_uiFromScene;
    int m_wcOperateMode;
    Class m_popToViewControllerClassWhenDelete;
    int m_searchScene;
    id m_userData;
    double m_CurrentWidth;
    ForwardMessageLogicController *m_forwardLogic;
    unsigned int _startTime;
    int m_uiAddFriendStatScene;
    int _m_qrCodeAddFriendScene;
    unsigned int _searchFromIndex;
    NSMutableDictionary *_verifyUserInfoList;
    NSString *_searchId;
    NSString *_searchKeyword;
    NSString *_searchExtraParamsString;
    CMessageWrap *_sourceMsg;
    NSString *_reportInfo;
}

- (void).cxx_destruct;
- (unsigned int)GetFromScene;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)bindPhoneReturn;
- (void)checkNeedForcedUpdateForMemberDetail;
- (void)confirmExpose:(unsigned int)arg1;
- (void)contactVerifyOk:(id)arg1;
- (void)copyContactField:(id)arg1 toContact:(id)arg2;
- (void)dealloc;
- (void)delAllMsg;
- (void)doReset;
- (id)getContactVerifyLogic;
- (id)getCurrentViewController;
- (id)getSearchId;
- (id)getUserData;
- (id)getViewController;
- (id)init;
- (void)initSystemPluginData:(int)arg1;
- (id)initWithTitle:(id)arg1;
- (_Bool)isInMyContactList;
- (void)jumpToContentViewController:(id)arg1;
@property(nonatomic) __weak id <ContactInfoViewControllerDelegate> m_InfoDelegate; // @synthesize m_InfoDelegate;
@property(nonatomic) _Bool m_bPopToRootWhenDelete; // @synthesize m_bPopToRootWhenDelete;
@property(retain, nonatomic) CContact *m_chatContact; // @synthesize m_chatContact;
@property(retain, nonatomic) CContact *m_contact; // @synthesize m_contact;
@property(nonatomic) __weak id <contactInfoDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) NSString *m_nsLocation; // @synthesize m_nsLocation;
@property(nonatomic) Class m_popToViewControllerClassWhenDelete; // @synthesize m_popToViewControllerClassWhenDelete;
@property(nonatomic) int m_qrCodeAddFriendScene; // @synthesize m_qrCodeAddFriendScene=_m_qrCodeAddFriendScene;
@property(nonatomic) int m_searchScene; // @synthesize m_searchScene;
@property(nonatomic) int m_uiAddFriendStatScene; // @synthesize m_uiAddFriendStatScene;
@property(nonatomic) unsigned int m_uiFromScene; // @synthesize m_uiFromScene;
@property(nonatomic) unsigned int m_uiVerify; // @synthesize m_uiVerify;
@property(retain, nonatomic) id m_userData; // @synthesize m_userData;
- (void)onAddToContact;
- (void)onDeleteContact:(id)arg1;
- (void)onExpose;
- (_Bool)onFilterSendReceiver:(id)arg1;
- (void)onFriendRequestSend;
- (void)onHDHeadImageWillAppear;
- (void)onHDHeadImageWillDisappear;
- (void)onModifyContact:(id)arg1;
- (void)onNewMessage:(id)arg1;
- (void)onNewMessageWithPushOnTop:(id)arg1;
- (void)onPopViewController:(_Bool)arg1;
- (void)onProfileChange;
- (void)onRemoveContact;
- (void)onSayHello;
- (void)onSayHelloViewSendSayHello:(id)arg1;
- (void)onSendVerifyMsg;
- (void)onShareMyFriend;
- (void)onStrangerContactUpdated:(id)arg1;
- (void)onTalk:(id)arg1;
- (void)onVerifyOK;
- (void)onVerifyOKWithContact:(id)arg1;
- (void)onWCGroupAddMemberReturn:(_Bool)arg1 group:(id)arg2;
- (void)onWCGroupModMemberReturn:(_Bool)arg1 group:(id)arg2;
- (void)onWCGroupRemoveMemberReturn:(_Bool)arg1 group:(id)arg2;
- (void)reloadContactAssist;
- (void)reloadData;
- (void)reloadFloatView;
- (void)reloadView;
@property(retain, nonatomic) NSString *reportInfo; // @synthesize reportInfo=_reportInfo;
@property(retain, nonatomic) NSString *searchExtraParamsString; // @synthesize searchExtraParamsString=_searchExtraParamsString;
@property(nonatomic) unsigned int searchFromIndex; // @synthesize searchFromIndex=_searchFromIndex;
@property(retain, nonatomic) NSString *searchId; // @synthesize searchId=_searchId;
@property(retain, nonatomic) NSString *searchKeyword; // @synthesize searchKeyword=_searchKeyword;
@property(retain, nonatomic) CMessageWrap *sourceMsg; // @synthesize sourceMsg=_sourceMsg;
@property(retain, nonatomic) NSMutableDictionary *verifyUserInfoList; // @synthesize verifyUserInfoList=_verifyUserInfoList;
- (void)startLoadingWithText:(id)arg1;
- (void)statBanner;
- (void)stopLoadingWithFailText:(id)arg1;
- (void)stopLoadingWithOKText:(id)arg1;
- (id)tagForActivePage;
- (id)tagForCurrentPage;
- (void)updateContactFromServer;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidBePushed:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

