//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EJBindingEventedBase.h"

#import "EJDrawable.h"

@class EJTexture, NSOperation, NSString;

@interface EJBindingImage : EJBindingEventedBase <EJDrawable>
{
    EJTexture *texture;
    NSString *path;
    _Bool loading;
    NSOperation *loadCallback;
}

+ (id)_const_nodeName;
+ (id)_const_tagName;
+ (void *)_ptr_to_get_complete;
+ (void *)_ptr_to_get_height;
+ (void *)_ptr_to_get_instance;
+ (void *)_ptr_to_get_src;
+ (void *)_ptr_to_get_width;
+ (void *)_ptr_to_set_src;
- (struct OpaqueJSValue *)_get_complete:(struct OpaqueJSContext *)arg1;
- (struct OpaqueJSValue *)_get_height:(struct OpaqueJSContext *)arg1;
- (struct OpaqueJSValue *)_get_instance:(struct OpaqueJSContext *)arg1;
- (struct OpaqueJSValue *)_get_src:(struct OpaqueJSContext *)arg1;
- (struct OpaqueJSValue *)_get_width:(struct OpaqueJSContext *)arg1;
- (void)_set_src:(struct OpaqueJSContext *)arg1 value:(struct OpaqueJSValue *)arg2;
- (void)beginLoad;
- (void)dealloc;
- (void)endLoad;
- (void)prepareGarbageCollection;
- (void)setTexture:(id)arg1 path:(id)arg2;
@property(readonly, nonatomic) EJTexture *texture; // @synthesize texture;
- (void)triggerEvent:(id)arg1;

@end

