//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EJBindingEventedBase.h"

#import "EJDeviceMotionDelegate.h"

@class CMMotionManager;

@interface EJBindingDeviceMotion : EJBindingEventedBase <EJDeviceMotionDelegate>
{
    CMMotionManager *motionManager;
    struct OpaqueJSValue *params[13];
    float interval;
}

+ (void *)_ptr_to_get_interval;
+ (void *)_ptr_to_get_onacceleration;
+ (void *)_ptr_to_get_ondevicemotion;
+ (void *)_ptr_to_set_onacceleration;
+ (void *)_ptr_to_set_ondevicemotion;
- (struct OpaqueJSValue *)_get_interval:(struct OpaqueJSContext *)arg1;
- (void)createWithJSObject:(struct OpaqueJSValue *)arg1 scriptView:(id)arg2;
- (void)dealloc;
- (void)prepareGarbageCollection;
- (void)triggerDeviceMotionEvents;
- (void)triggerEventWithAccelerometerData:(id)arg1;
- (void)triggerEventWithMotion:(id)arg1;

@end

