//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface EJFontLayout : NSObject
{
    NSData *glyphLayout;
    CDStruct_de2edefb metrics;
    long long glyphCount;
    CDStruct_f80ef75d *_layout;
}

- (void)dealloc;
@property(readonly, nonatomic) long long glyphCount; // @synthesize glyphCount;
- (CDStruct_f80ef75d *)glyphLayout;
- (id)initWithGlyphLayout:(id)arg1 glyphCount:(long long)arg2 metrics:(CDStruct_de2edefb)arg3;
@property(readonly, nonatomic) CDStruct_f80ef75d *layout; // @synthesize layout=_layout;
@property(readonly, nonatomic) CDStruct_de2edefb metrics; // @synthesize metrics;

@end

