//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "UIKeyInput.h"

@class NSObject<EJKeyInputDelegate>, NSString;

@interface EJKeyInputResponder : UIResponder <UIKeyInput>
{
    NSObject<EJKeyInputDelegate> *_delegate;
}

- (_Bool)becomeFirstResponder;
- (_Bool)canBecomeFirstResponder;
@property(nonatomic) NSObject<EJKeyInputDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)deleteBackward;
@property(readonly, nonatomic) _Bool hasText;
- (void)insertText:(id)arg1;
- (id)nextResponder;
- (_Bool)resignFirstResponder;

// Remaining properties
@property(nonatomic) long long autocapitalizationType;
@property(nonatomic) long long autocorrectionType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool enablesReturnKeyAutomatically;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long keyboardAppearance;
@property(nonatomic) long long keyboardType;
@property(nonatomic) long long returnKeyType;
@property(nonatomic, getter=isSecureTextEntry) _Bool secureTextEntry;
@property(nonatomic) long long smartDashesType;
@property(nonatomic) long long smartInsertDeleteType;
@property(nonatomic) long long smartQuotesType;
@property(nonatomic) long long spellCheckingType;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSString *textContentType;

@end

