//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EJKeyInputResponder, NSString, UIResponder;

@protocol EJKeyInputDelegate <NSObject>
- (UIResponder *)nextResponderForKeyInput:(EJKeyInputResponder *)arg1;

@optional
- (_Bool)hasText;
- (void)keyInput:(EJKeyInputResponder *)arg1 insertText:(NSString *)arg2;
- (void)keyInputDidBecomeFirstResponder:(EJKeyInputResponder *)arg1;
- (void)keyInputDidDeleteBackwards:(EJKeyInputResponder *)arg1;
- (void)keyInputDidResignFirstResponderStatus:(EJKeyInputResponder *)arg1;
@end

