//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "MMWebImageViewDelegate.h"

@class MMWebImageView, NSString, UIView;

@interface EmoticonTabItemView : MMUIView <MMWebImageViewDelegate>
{
    _Bool _needConvertToGrayImage;
    _Bool _selected;
    MMWebImageView *_m_webImageView;
    UIView *_lineView;
}

- (void).cxx_destruct;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) MMWebImageView *m_webImageView; // @synthesize m_webImageView=_m_webImageView;
@property(nonatomic) _Bool needConvertToGrayImage; // @synthesize needConvertToGrayImage=_needConvertToGrayImage;
- (void)onLoadImageOK:(id)arg1;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
- (void)setNormalImage:(id)arg1;
- (void)setNormalImageUrl:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

