//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBMessageObserverDelegate.h"

@class NSDictionary, NSMutableArray, NSString;

@interface FaceRecog3rdVerifyConfirmLogic : MMObject <PBMessageObserverDelegate>
{
    id <FaceRecog3rdVerifyConfirmLogicDelegate> _delegate;
    NSMutableArray *_confirmInfos;
    NSDictionary *_prompts;
    NSString *_bizNickName;
    NSString *_headerPromptWording;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
@property(copy, nonatomic) NSString *bizNickName; // @synthesize bizNickName=_bizNickName;
@property(retain, nonatomic) NSMutableArray *confirmInfos; // @synthesize confirmInfos=_confirmInfos;
- (void)dealloc;
@property(nonatomic) __weak id <FaceRecog3rdVerifyConfirmLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (id)getBizNickName;
- (id)getConfirmInfos;
- (id)getHeaderPromptWording;
- (id)getPrompts;
- (void)handleGetConfirmInfo:(id)arg1;
@property(copy, nonatomic) NSString *headerPromptWording; // @synthesize headerPromptWording=_headerPromptWording;
- (id)init;
@property(retain, nonatomic) NSDictionary *prompts; // @synthesize prompts=_prompts;
- (void)resetLogicState;
- (_Bool)startGetConfirmInfo:(id)arg1 verifyInfo:(id)arg2;

@end

