//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FaceProHandle : NSObject
{
    struct FacePro *mFacePro;
    struct mutex mtx;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
- (int)engineFaceProcess:(struct opaqueCMSampleBuffer *)arg1 image:(id *)arg2 mode:(_Bool)arg3;
- (vector_e0f2bd7e)engineGetAllMotion;
- (int)engineGetCurrMotion;
- (basic_string_a490aa4c)engineGetCurrMotionData;
- (basic_string_a490aa4c)engineGetData:(int)arg1;
- (void)engineGetFaceRect:(struct CGRect *)arg1;
- (int)engineGetFaceYaw;
- (int)engineGetPoseMotion;
- (basic_string_a490aa4c)engineGetReadNumbers;
- (void)engineGroupChange;
- (int)engineNextMotion;
- (int)engineRelease;
- (int)engineReleaseCurrMotion;
- (void)engineSetFaceFrame:(struct CGRect)arg1;
- (void)engineSetVoiceData:(char *)arg1 withSize:(int)arg2;
- (void)engineStartRecord;
- (basic_string_a490aa4c)engineVersion;
- (id)initWithConfig:(id)arg1 bioId:(id)arg2;
- (id)screenshotOfVideoStream:(struct __CVBuffer *)arg1;

@end

