//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class FTSSearchLocalPageResultWrap;

@interface FTSWebSearchLocalPageCell : UITableViewCell
{
    FTSSearchLocalPageResultWrap *_resultWrap;
    id <WebSearchLocalPageCellDelegate> _delegate;
}

+ (double)heightForData:(id)arg1;
- (void).cxx_destruct;
- (void)configureWithData:(id)arg1;
@property(nonatomic) __weak id <WebSearchLocalPageCellDelegate> delegate; // @synthesize delegate=_delegate;
- (id)makeNewButton:(id)arg1;
- (void)onClickButton:(id)arg1;

@end

