//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GetGameIndex2Response_Recommendation_Banner, GetGameIndex2Response_Recommendation_RecomItem;

@protocol GameCenterRecommendViewDelegate <NSObject>
- (void)onRecommendLowerItemClick:(GetGameIndex2Response_Recommendation_RecomItem *)arg1 IsLeft:(_Bool)arg2;
- (void)onRecommendUpperBannerClick:(GetGameIndex2Response_Recommendation_Banner *)arg1;
@end

