//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class BaseResponse, DownloadGuidance, GameManagementEntrance;

@interface GetGameIndexDownloadGuidanceResponse : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(retain, nonatomic) GameManagementEntrance *gameManagement; // @dynamic gameManagement;
@property(retain, nonatomic) DownloadGuidance *googlePlayTips; // @dynamic googlePlayTips;

@end

