//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IDCHostItem : NSObject
{
    NSString *origin;
    NSString *substitute;
    int priority;
}

- (void).cxx_destruct;
- (id)description;
- (id)init;
- (id)initWithOrigin:(id)arg1 Substitute:(id)arg2 Priority:(int)arg3;
@property(retain, nonatomic) NSString *origin; // @synthesize origin;
@property(nonatomic) int priority; // @synthesize priority;
@property(retain, nonatomic) NSString *substitute; // @synthesize substitute;

@end

