//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ReaderItemView.h"

#import "AsyncImageViewDelegate.h"

@class CAGradientLayer, CALayer, NSString, UIImageView;

@interface ImageReaderItemView : ReaderItemView <AsyncImageViewDelegate>
{
    UIImageView *m_imageIcon;
    CAGradientLayer *m_gradientLayer;
    CALayer *m_coverMaskLayer;
    unsigned int _imageCount;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int imageCount; // @synthesize imageCount=_imageCount;
- (void)onAsyncLoadImageOK:(id)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)topView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

