//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "H5GameViewControllerDelegate.h"
#import "IBackupExt.h"
#import "IContactVerifyExt.h"
#import "IFavoritesOnTopLogicExt.h"
#import "IMMWebViewKeepHolderMgrExt.h"
#import "IMigrationClientExt.h"
#import "IMusicPlayerExt.h"
#import "IOnlineClientMgrExt.h"
#import "IPublicWifiManagerExt.h"
#import "MFPushBannerDelegate.h"
#import "MFPushSystemMsgDelegate.h"

@class MFBackupBtn, MFBannerBtn, MFFavDetailBtn, MFMigrationBtn, MFMusicPlayBtn, MFPublicWifiBtn, MFPushBannerLogic, MFPushSystemMsgLogic, MFWeAppBtn, MFWebMMBtn, MFWebViewVCKeepHoldBtn, MMVoiceSearchBar, NSMutableArray, NSString;

@interface MainFrameHeaderLogic : MMObject <MFPushBannerDelegate, MFPushSystemMsgDelegate, IOnlineClientMgrExt, IMusicPlayerExt, IPublicWifiManagerExt, IMMWebViewKeepHolderMgrExt, IBackupExt, IMigrationClientExt, IContactVerifyExt, H5GameViewControllerDelegate, IFavoritesOnTopLogicExt>
{
    MMVoiceSearchBar *m_searchBar;
    NSMutableArray *m_bannerAry;
    _Bool m_bWebWXLogined;
    _Bool m_bBakChatStarted;
    MFWebMMBtn *m_webMMBtn;
    MFMusicPlayBtn *m_musicPlayBtn;
    MFPublicWifiBtn *m_publicWifiBtn;
    MFWebViewVCKeepHoldBtn *m_webViewRecoverBtn;
    MFBackupBtn *m_backupBtn;
    MFWeAppBtn *m_weappBtn;
    MFMigrationBtn *m_migrationBtn;
    MFBannerBtn *m_contactVerifyBtn;
    MFFavDetailBtn *m_MFFavDetailBtn;
    MFPushBannerLogic *m_pushBannerLogic;
    MFPushSystemMsgLogic *m_pushSystemMsgLogic;
    id <MainFrameHeaderDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)PopViewController;
- (void)PushViewController:(id)arg1;
- (void)addBannerBtn:(id)arg1 atIndex:(unsigned int)arg2 editable:(_Bool)arg3 withAnim:(_Bool)arg4;
- (void)addBannerBtn:(id)arg1 atIndex:(unsigned int)arg2 withAnim:(_Bool)arg3;
- (void)addBannerBtn:(id)arg1 withAnim:(_Bool)arg2;
@property(readonly, nonatomic) unsigned long long bannerCount;
- (_Bool)cellEditable:(unsigned long long)arg1;
- (void)dealloc;
- (void)delayHiddenMusicPlayBannerIfPlayerIdle:(id)arg1;
@property(nonatomic) __weak id <MainFrameHeaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteBanner:(unsigned long long)arg1;
- (void)dismissPushSystemMsg;
- (void)dismissSystemMessage;
- (id)getBanner:(unsigned long long)arg1;
- (void)initBackupButton;
- (void)initContactVerifyButton;
- (void)initHeader;
- (void)initMigrationButton;
- (void)initMusicPlayBtn;
- (void)initPublicWifiBtn:(id)arg1;
- (void)initPushBanner;
- (void)initWebMMBtn;
- (id)initWithViewControllerForSearch:(id)arg1;
- (void)makeSearchBar:(id)arg1;
- (void)onBackupNotifyCode:(unsigned long long)arg1;
- (void)onBackupTransferSpeed:(float)arg1;
- (void)onClientMigrationCurrentReceiveSize:(unsigned long long)arg1 totalSize:(unsigned long long)arg2;
- (void)onClientMigrationCurrentTransferSpeed:(float)arg1;
- (void)onClientMigrationNotifyCode:(unsigned long long)arg1;
- (void)onClientMigrationNotifySessionCurrent:(unsigned long long)arg1 totalSession:(unsigned long long)arg2;
- (void)onGameViewClosed;
- (void)onHidePushBanner;
- (void)onKeepHoldWebViewVCForNewMainFrameBannerStatusChangedIsAddKeep:(_Bool)arg1;
- (void)onLoginWeb;
- (void)onLogoutWeb;
- (void)onMusicPlayInnerStatusChanged:(unsigned long long)arg1 musicInfo:(id)arg2 errInfo:(id)arg3;
- (void)onProgressCurrentSession:(unsigned long long)arg1 totalSession:(unsigned long long)arg2;
- (void)onPublicWifiStatusChangedWithApBase:(id)arg1;
- (void)onShowPushBanner;
- (void)onStartBackup;
- (void)onStartContactVerify;
- (void)onStartMigration;
- (void)onTerminateBackup;
- (void)onTerminateContactVerify;
- (void)onTerminateMigration;
- (void)openContactInfo:(id)arg1;
- (void)processMusicPlayBtn:(_Bool)arg1;
- (void)processPublicWifiBtn:(_Bool)arg1 apBase:(id)arg2;
- (void)registerExt;
- (void)reloadMusicBanner:(id)arg1;
- (void)removeBannerBtn:(id)arg1;
- (void)removeBannerBtnWithoutAnim:(id)arg1;
@property(readonly, nonatomic) MMVoiceSearchBar *searchBar; // @synthesize searchBar=m_searchBar;
- (void)showBackupViewController;
- (void)showCancelMusicPlay;
- (void)showConversionOnTop:(_Bool)arg1;
- (void)showLogoutWebOnline;
- (void)showMigrationViewController;
- (void)showPrivacyVC;
- (void)showPublicWifiView;
- (void)showPushSystemMsg;
- (void)showReadingFavDetail;
- (void)showReadingWebview;
- (void)trigBanner:(unsigned long long)arg1;
- (void)unRegisterExt;
- (void)updateMusicPlayBanner;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

