//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface MassSendContact : NSObject <WCTTableCoding>
{
    NSString *m_nsUsrName;
    NSString *m_nsDetail;
    unsigned int m_uiToListCount;
    unsigned int ConIntRes2;
    NSString *ConStrRes1;
    NSString *ConStrRes2;
}

+ (const struct WCTPropertyList *)AllProperties;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTProperty *)ConIntRes2;
+ (const struct WCTProperty *)ConStrRes1;
+ (const struct WCTProperty *)ConStrRes2;
+ (CDUnknownBlockType)PropertyNamed;
+ (const struct WCTProperty *)m_nsDetail;
+ (const struct WCTProperty *)m_nsUsrName;
+ (const struct WCTProperty *)m_uiToListCount;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
- (void).cxx_destruct;
@property(nonatomic) unsigned int ConIntRes2; // @synthesize ConIntRes2;
@property(retain, nonatomic) NSString *ConStrRes1; // @synthesize ConStrRes1;
@property(retain, nonatomic) NSString *ConStrRes2; // @synthesize ConStrRes2;
- (void)dealloc;
- (id)description;
- (id)init;
@property(retain, nonatomic) NSString *m_nsDetail; // @synthesize m_nsDetail;
@property(retain, nonatomic) NSString *m_nsUsrName; // @synthesize m_nsUsrName;
@property(nonatomic) unsigned int m_uiToListCount; // @synthesize m_uiToListCount;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

