//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMComponentData : NSObject
{
    _Bool hideLine;
    _Bool _bUseCardStyle;
    _Bool _bUseSearchStyle;
    struct CGRect rect;
}

@property(nonatomic) _Bool bUseCardStyle; // @synthesize bUseCardStyle=_bUseCardStyle;
@property(nonatomic) _Bool bUseSearchStyle; // @synthesize bUseSearchStyle=_bUseSearchStyle;
@property(nonatomic) _Bool hideLine; // @synthesize hideLine;
@property(nonatomic) struct CGRect rect; // @synthesize rect;

@end

