//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMDumpDataInterface : NSObject
{
}

+ (void)deleteDumpDataWithReportID:(id)arg1 andReportType:(unsigned long long)arg2;
+ (id)getDumpDataWithReportID:(id)arg1 andReportType:(unsigned long long)arg2;
+ (id)getDumpDataWithReportIDArray:(id)arg1 andReportType:(unsigned long long)arg2;
+ (id)getReportType:(id)arg1;
+ (id)pathToCrashReportWithID:(id)arg1 andreportType:(unsigned long long)arg2;

@end

