//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface MMFPSLogObject : NSObject
{
    NSString *_scene;
    NSDate *_startTime;
    NSDate *_endTime;
    double _totalFrameTime;
    long long _totalDropFrame;
}

- (void).cxx_destruct;
- (id)description;
@property(retain, nonatomic) NSDate *endTime; // @synthesize endTime=_endTime;
@property(retain, nonatomic) NSString *scene; // @synthesize scene=_scene;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
@property(nonatomic) long long totalDropFrame; // @synthesize totalDropFrame=_totalDropFrame;
@property(nonatomic) double totalFrameTime; // @synthesize totalFrameTime=_totalFrameTime;

@end

