//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMImageClipUtil : NSObject
{
}

+ (id)clipImage:(id)arg1 withData:(id)arg2 toTargetSize:(struct CGSize)arg3;
+ (char *)convertUIImageToBitmapRGBA8:(id)arg1 WidthStep:(int *)arg2;
+ (struct CGContext *)newBitmapRGBA8ContextFromImage:(struct CGImage *)arg1;

@end

