//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ScreenshotView, UIImageView;

@interface MMMagnifiterView : UIView
{
    UIImageView *m_oImageView;
    ScreenshotView *m_oScreenshotView;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setTouchPoint:(struct CGPoint)arg1;
- (void)setViewToMagnify:(id)arg1;

@end

