//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FPSTracerDelegate.h"
#import "IMainFrameScrollExt.h"
#import "ITimeLineViewScrollExt.h"
#import "MMUIViewControllerExt.h"

@class NSObject<OS_dispatch_queue>, NSString, NSThread, WXGFPSTracer, WXGMainThreadHandler;

@interface MMMonitorMgr : NSObject <FPSTracerDelegate, MMUIViewControllerExt, ITimeLineViewScrollExt, IMainFrameScrollExt>
{
    NSThread *m_monitorThread;
    _Bool m_bStop;
    unsigned long long m_nIntervalTime;
    unsigned long long m_nLastTimeInterval;
    struct vector<unsigned long, std::__1::allocator<unsigned long>> m_vecLastMainThreadCallStack;
    unsigned long long m_nSum;
    _Bool m_isBackgroundStartUp;
    unsigned long long m_blockDiffTime;
    NSString *m_potenHandledLagFile;
    float m_cpuUsage;
    unsigned int m_firstSleepTime;
    struct __CFRunLoopObserver *m_runLoopBeginObserver;
    struct __CFRunLoopObserver *m_runLoopEndObserver;
    struct __CFRunLoopObserver *m_initializationBeginRunloopObserver;
    struct __CFRunLoopObserver *m_initializationEndRunloopObserver;
    _Bool m_bDebugInXcode;
    WXGMainThreadHandler *m_pointMainThreadHandler;
    WXGFPSTracer *m_fpsTracer;
    NSObject<OS_dispatch_queue> *m_ftsDumpQueue;
    unsigned long long m_mainSemaphore;
    NSString *m_trackScene;
    _Bool m_bFirstActive;
    _Bool m_bInSuspend;
    _Bool m_bMonitor;
    _Bool m_bLaunchLagMonitorOver;
}

+ (id)shareInstance;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)MMUIViewControllerDidAppear:(id)arg1;
- (void)MMUIViewControllerDidDisappear:(id)arg1;
- (void)MMUIViewControllerWillAppear:(id)arg1;
- (void)MMUIViewControllerWillDisppear:(id)arg1;
- (void)addMonitorThread;
- (void)addRunLoopObserver;
- (unsigned long long)check;
- (void)clearDumpInBackgroundLaunch;
- (void)dealloc;
- (void)didBecomeActive;
- (void)didEnterBackground;
- (unsigned long long)diffTime:(struct timeval *)arg1 endTime:(struct timeval *)arg2;
- (id)dumpFileWithType:(unsigned long long)arg1;
- (id)getLaunchBlockRecordFilePath;
- (void)handleBackgroundLaunch;
- (id)init;
- (_Bool)isDumpTypeRelatedToFOOM:(unsigned long long)arg1;
@property(nonatomic) _Bool m_bLaunchLagMonitorOver; // @synthesize m_bLaunchLagMonitorOver;
@property(nonatomic) _Bool m_bMonitor; // @synthesize m_bMonitor;
- (_Bool)needFilter;
- (void)onFrameDroppedTooMuch;
- (void)onMainFrameBeginScroll;
- (void)onMainFrameEndScroll;
- (void)onTimeLineBeginScroll;
- (void)onTimeLineEndScroll;
- (void)refreshMonitorSetting;
- (void)removeRunLoopObserver;
- (void)reportWithID:(int)arg1 key:(int)arg2 value:(int)arg3;
- (void)resetStatus;
- (void)saveBlockTimeToLagFile;
- (void)setCPUUsagePercent:(float)arg1;
- (void)setLaunchOverByTimer;
- (void)setPerStackInterval:(unsigned int)arg1;
- (void)setRunloopTimeOut:(unsigned long long)arg1 andCheckPeriodTime:(unsigned int)arg2;
- (void)stop;
- (void)threadProc;
- (void)willResignActive;
- (void)willSuspend;
- (void)willTerminate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

