//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMMP4Parser : NSObject
{
}

+ (float)parserMvhd:(id)arg1;
+ (float)parserToGetDurationWithFilePath:(id)arg1;
+ (void)seekToMvhd:(id)arg1 boxSize:(unsigned int)arg2;

@end

