//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSString;

@interface MMMusicPlayerErrInfo : NSObject
{
    long long _errCode;
    NSString *_errMsg;
    NSError *_innerError;
}

- (void).cxx_destruct;
- (id)description;
@property(nonatomic) long long errCode; // @synthesize errCode=_errCode;
@property(retain, nonatomic) NSString *errMsg; // @synthesize errMsg=_errMsg;
@property(retain, nonatomic) NSError *innerError; // @synthesize innerError=_innerError;

@end

