//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMPathComponent : NSObject
{
    char *m_path;
    unsigned long long m_pathBufSize;
    unsigned long long m_pathSize;
}

- (_Bool)addComponent:(const char *)arg1;
- (void)dealloc;
- (id)init;
- (const char *)path;
- (void)removeLastComponent;
- (void)reset;

@end

