//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMPathUtility : NSObject
{
}

+ (id)DBREcoverExportDBPathWithDBName:(id)arg1;
+ (id)DBREcoverExportSQLPathWithDBName:(id)arg1;
+ (id)DBRecoverBackupDir;
+ (id)DBRecoverConfigPath;
+ (id)DBRecoverDBBackupDirWithDBName:(id)arg1;
+ (id)DBRecoverDir;
+ (id)DBRecoverTempDir;
+ (id)DiskUsageConfigDataPath;
+ (id)DiskUsageDir;
+ (id)DiskUsageReportDataPath;
+ (id)DiskUsageScanDataPath;
+ (id)DiskUsageStatusPath;
+ (id)GetCurrentUserLibraryCachePath;
+ (id)GetDocumentPath;
+ (id)GetLibraryCachePath;
+ (id)MossDir;

@end

