//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMPieChartView, UIColor;

@protocol MMPieChartDataSource <NSObject>
- (unsigned long long)numberOfPiesInChart:(MMPieChartView *)arg1;
- (double)pieChart:(MMPieChartView *)arg1 valueForPieAtIndex:(unsigned long long)arg2;

@optional
- (UIColor *)pieChart:(MMPieChartView *)arg1 colorForPieAtIndex:(unsigned long long)arg2;
- (double)pieChart:(MMPieChartView *)arg1 radiuForPieAtIndex:(unsigned long long)arg2;
@end

