//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IBackupExt.h"
#import "IChatMigrationExt.h"
#import "INewABTestMgrExt.h"
#import "IVOIPWindowExt.h"

@class NSMutableArray, NSString;

@interface MMPowerMgr : NSObject <INewABTestMgrExt, IVOIPWindowExt, IBackupExt, IChatMigrationExt>
{
    _Bool m_bLowPowerMode;
    NSMutableArray *m_minuteCPUUsageArray;
    double m_foregroundTime;
    double m_backgroundTime;
    _Bool m_bQuickSyncFilter;
    _Bool m_bBackgroundControl;
    _Bool m_bMonitorCPUAverage;
    unsigned int _bStopMonitorCPUAverageCount;
}

+ (float)getCurrentCpuUsage;
+ (long long)getResidentMemory;
+ (long long)getVirtualMemory;
+ (id)shareInstance;
- (void).cxx_destruct;
@property unsigned int bStopMonitorCPUAverageCount; // @synthesize bStopMonitorCPUAverageCount=_bStopMonitorCPUAverageCount;
- (void)checkABTest;
- (_Bool)controlBackgroundTime;
- (_Bool)cultivateCpuUsage:(float)arg1 periodTime:(float)arg2;
- (void)dealloc;
- (_Bool)filterQuickSync;
- (double)getBackgroundTime;
- (double)getForegroundTime;
- (id)init;
- (_Bool)isLowPowerMode;
- (void)onMigrationStopWorking;
- (void)onMigrationWorking;
- (void)onModifyABTestItem:(id)arg1 bizId:(id)arg2 abTestItem:(id)arg3;
- (void)onStartBackup;
- (void)onTerminateBackup;
- (void)onVoipWindowDidAppear;
- (void)onVoipWindowDisappear;
- (void)p_setPowerMode;
- (void)processEnterBackground;
- (void)processEnterForeground;
- (void)processPowerModeChange;
- (void)startCameraScan;
- (void)stopCameraScan;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

