//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIImage;

@interface MMScrollActionSheetItem : NSObject
{
    UIImage *_iconImg;
    NSString *_title;
    id _userInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *iconImg; // @synthesize iconImg=_iconImg;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;

@end

