//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CMessageWrap;

@protocol MsgDataDownloadDelegate

@optional
- (void)onDownloadCancel:(CMessageWrap *)arg1;
- (void)onDownloadCommonFail:(CMessageWrap *)arg1;
- (void)onDownloadExpireFail:(CMessageWrap *)arg1;
- (void)onDownloadSuccess:(CMessageWrap *)arg1;
@end

