//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSString;

@interface MSThreadInfo : NSObject <PBCoding>
{
    NSString *threadName;
    unsigned long long allocSize;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long allocSize; // @synthesize allocSize;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
@property(retain, nonatomic) NSString *threadName; // @synthesize threadName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

