//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PoseDetect : NSObject
{
    struct PoseLivenessDetector *liveDetector;
}

+ (id)sharedManager;
- (id)init;
- (_Bool)livePoseDetect:(struct _TC_FaceShape)arg1 withLiveType:(int)arg2 withImg:(struct Mat *)arg3 withRes:(int *)arg4;
- (void)resetPoseDetect;

@end

