//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Q2dStatisticData : NSObject
{
    int _tencentHitCount;
    int _worldmapHitCount;
    int _tencentMissCount;
    int _worldmapMissCount;
    int _tencentTileUpdateCount;
    int _tencentTileKeepCount;
}

- (id)init;
- (void)reset;
@property(nonatomic) int tencentHitCount; // @synthesize tencentHitCount=_tencentHitCount;
@property(nonatomic) int tencentMissCount; // @synthesize tencentMissCount=_tencentMissCount;
@property(nonatomic) int tencentTileKeepCount; // @synthesize tencentTileKeepCount=_tencentTileKeepCount;
@property(nonatomic) int tencentTileUpdateCount; // @synthesize tencentTileUpdateCount=_tencentTileUpdateCount;
@property(nonatomic) int worldmapHitCount; // @synthesize worldmapHitCount=_worldmapHitCount;
@property(nonatomic) int worldmapMissCount; // @synthesize worldmapMissCount=_worldmapMissCount;
- (id)urlQuery;

@end

