//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSString;

@interface ShakeCardRedDot : MMObject <PBCoding>
{
    _Bool shakeHasRead;
    NSString *redDotId;
    NSString *redDotDesc;
    NSString *redDotText;
}

+ (void)initialize;
- (void).cxx_destruct;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
@property(retain, nonatomic) NSString *redDotDesc; // @synthesize redDotDesc;
@property(retain, nonatomic) NSString *redDotId; // @synthesize redDotId;
@property(retain, nonatomic) NSString *redDotText; // @synthesize redDotText;
@property(nonatomic) _Bool shakeHasRead; // @synthesize shakeHasRead;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

