//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CommonMessageCellView.h"

#import "ILinkEventExt.h"
#import "ITranslateMsgMgrExt.h"
#import "MMTipsViewControllerDelegate.h"
#import "RichTextLayoutDelegate.h"
#import "TextFloatPreviewDelegate.h"
#import "WCActionSheetDelegate.h"

@class MMTipsViewController, NSArray, NSString, NavigateLogicController, RichTextView, TextMessageViewModel, TopLeftLabel, UIActivityIndicatorView, UIImageView, UILabel, UIView, WCUIActionSheet;

@interface TextMessageCellView : CommonMessageCellView <ILinkEventExt, RichTextLayoutDelegate, WCActionSheetDelegate, MMTipsViewControllerDelegate, TextFloatPreviewDelegate, ITranslateMsgMgrExt>
{
    RichTextView *m_richTextView;
    MMTipsViewController *m_oTranslateIntroView;
    WCUIActionSheet *m_uiActionSheet;
    NavigateLogicController *m_navigationLogic;
    TopLeftLabel *m_oTranslateTextLabel;
    UIView *m_translateView;
    UIActivityIndicatorView *m_oTranslateLoadingView;
    UILabel *m_translateSuccessLabel;
    UIImageView *m_translateSuccessIconView;
    NSArray *m_translateMenus;
}

- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (_Bool)addCoverViewToControllerTable;
- (void)addMagicTapActions:(id)arg1;
- (void)addTranslateViewMenus;
- (_Bool)canBeReused;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPeek;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)canShowTranslateMenuItem;
- (double)contentViewCenterY;
- (void)dealloc;
- (id)getOperateMenuItem;
- (id)getPreviewLinkForLocation:(struct CGPoint)arg1 inView:(id)arg2;
- (struct CGRect)getPreviewLinkFrameForLocation:(struct CGPoint)arg1 inView:(id)arg2;
- (_Bool)handleMagicTapAction:(id)arg1;
- (void)handleTranslateMenuWillHideMenuNotification:(id)arg1;
- (_Bool)highLightSearchKeyWords:(id)arg1;
- (void)initRichTextView;
- (void)initTranslateTextLabel;
- (void)initTranslateView;
- (_Bool)isNetworkAvailable;
- (_Bool)isTouchInView:(id)arg1;
- (void)layoutContentView;
- (void)onAddressClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onClickTipsBtn:(id)arg1 Index:(long long)arg2 tipTag:(long long)arg3;
- (void)onCopy:(id)arg1;
- (void)onCopyLinkText:(id)arg1;
- (void)onCopyTranslate:(id)arg1;
- (void)onDisappear;
- (void)onDoubleTapTranslateView:(id)arg1;
- (void)onFavoriteTranslate:(id)arg1;
- (void)onForwardTranslate:(id)arg1;
- (void)onHide;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onLinkHighlighted:(_Bool)arg1 url:(id)arg2;
- (void)onLinkLongPressed:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onLongPressTranslateView:(id)arg1;
- (void)onLongTouch;
- (void)onPhoneClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onReTryTranslate:(id)arg1;
- (void)onTapTranslateView:(id)arg1;
- (void)onTouchDownRepeat;
- (void)onTranslateMessageChanged:(id)arg1;
- (void)onTranslateMessageFailed:(id)arg1 errTip:(id)arg2;
- (void)onTranslateMsg:(id)arg1;
- (void)onWeAppLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onWindowHide;
- (id)operationMenuItems;
- (void)prepareForReuse;
- (_Bool)preventLongPressLink;
- (struct CGRect)previewingSourceRectForLocation:(struct CGPoint)arg1 inCoordinateView:(id)arg2;
- (void)retryTranslate;
- (void)setHighlighted:(_Bool)arg1;
- (void)setNeedsDisplay;
- (void)setTranslateText;
- (void)setViewModel:(id)arg1;
- (_Bool)touchIntoSelectCopyState;
- (void)translateMsg;
- (void)triggerLongPressFor3DTouchAtLocation:(struct CGPoint)arg1 inCoordinateView:(id)arg2;
- (void)updateContentOffset:(_Bool)arg1;
- (void)updateStatus;
- (void)updateTranslateStatusButton;
- (void)updateTranslateSuccessView;
- (id)viewControllerToPreviewWithFromController:(id)arg1 forLocation:(struct CGPoint)arg2 inCoordinateView:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) TextMessageViewModel *viewModel; // @dynamic viewModel;

@end

