//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface TLDSharkReqItem : NSObject
{
    int _csID;
    int _scID;
    int _tag;
    NSString *_url;
    NSData *_reqData;
}

- (void).cxx_destruct;
@property(nonatomic) int csID; // @synthesize csID=_csID;
@property(retain, nonatomic) NSData *reqData; // @synthesize reqData=_reqData;
@property(nonatomic) int scID; // @synthesize scID=_scID;
@property(nonatomic) int tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;

@end

