//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TLDXXTeaUtil : NSObject
{
}

+ (id)QQPimTccCompress:(id)arg1;
+ (id)QQPimTccDeCompress:(id)arg1;
+ (id)TeaDecrypt:(id)arg1;
+ (id)TeaDecrypt:(id)arg1 withKey:(id)arg2;
+ (id)TeaEncrypt:(id)arg1;
+ (id)TeaEncrypt:(id)arg1 withKey:(id)arg2;

@end

