//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TXCBasePlayer.h"

#import "TXIAudioPlayDelegate.h"

@class NSMutableArray, NSString;

@interface TXCAudioPlayer : TXCBasePlayer <TXIAudioPlayDelegate>
{
    NSMutableArray *_playPackets;
    struct TXCAudioSpeeder *_audioSpeeder;
    struct TXCAudioJitterBuffer *_audioJitterBuffer;
    struct TXCAudioPlayerCallback *_playerCallback;
    struct TXCMutex _audioPlayLock;
    long long _audioType;
    long long _cacheDuration;
    _Bool _isHWAcceleration;
    _Bool _autojustCache;
    _Bool _isRealPlay;
    _Bool _canSpeed;
    float _cacheTime;
    float _autoAdjustMaxCache;
    float _autoAdjustMinCache;
    id <TXIAudioPlayDelegate> _delegate;
    id <TXINotifyDelegate> _notifyDelegate;
}

+ (void)setAudioMode:(long long)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) int audioJitter;
@property(nonatomic) float autoAdjustMaxCache; // @synthesize autoAdjustMaxCache=_autoAdjustMaxCache;
@property(nonatomic) float autoAdjustMinCache; // @synthesize autoAdjustMinCache=_autoAdjustMinCache;
@property(nonatomic) _Bool autojustCache; // @synthesize autojustCache=_autojustCache;
@property(readonly, nonatomic) long long cacheDuration;
@property(nonatomic) float cacheTime; // @synthesize cacheTime=_cacheTime;
@property(nonatomic) _Bool canSpeed; // @synthesize canSpeed=_canSpeed;
@property(readonly, nonatomic) unsigned long long curNetRecvTS;
@property(readonly, nonatomic) unsigned long long curPlayTS;
- (void)dealloc;
@property(nonatomic) __weak id <TXIAudioPlayDelegate> delegate; // @synthesize delegate=_delegate;
- (id)getReportInfo;
- (id)init;
@property(nonatomic) _Bool isHWAcceleration; // @synthesize isHWAcceleration=_isHWAcceleration;
@property(nonatomic) _Bool isRealPlay; // @synthesize isRealPlay=_isRealPlay;
@property(nonatomic) __weak id <TXINotifyDelegate> notifyDelegate; // @synthesize notifyDelegate=_notifyDelegate;
- (long long)pausePlay;
- (long long)playAudio:(id)arg1;
@property(readonly, nonatomic) float playSpeed;
- (id)queryData:(int)arg1;
- (long long)resetPlay;
- (long long)resumePlay;
- (long long)startPlay;
- (long long)stopPlay;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

