//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TXCCommonHelper : NSObject
{
}

+ (int)convSampleRateEnum:(long long)arg1;
+ (long long)convSampleRateValue:(int)arg1;
+ (_Bool)copyField:(id)arg1 dstKey:(id)arg2 srcDict:(id)arg3 srcKey:(id)arg4;
+ (id)getAppVersion;
+ (_Bool)isSuitableMachine:(int)arg1;
+ (void)setAppVersion:(id)arg1;

@end

