//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TXCFilterGroup.h"

@class TXCLookupFilter, TXCPicture, UIImage;

@interface TXCFilterFilter : TXCFilterGroup
{
    TXCLookupFilter *inputFilter;
    TXCPicture *lookupImageSource;
    double mixDegree;
    UIImage *filterImagae;
}

- (void).cxx_destruct;
- (id)init;
- (void)newFrameReadyAtTime:(CDStruct_1b6d18a9)arg1 atIndex:(long long)arg2;
- (void)setFilterImage:(id)arg1;
- (void)setFilterMixLevel:(float)arg1;

@end

