//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TXIModule.h"

@class CAEAGLLayer, CALayer, EAGLContext, NSString, TXCModule, TXCameraFocusSquare, UITapGestureRecognizer;

@interface TXCRenderView : UIView <TXIModule>
{
    unsigned long long _lastCalculateTS;
    unsigned long long _lastRenderFrameCount;
    unsigned long long _renderFrameCount;
    unsigned long long _lastRenderTS;
    unsigned long long _blockCount500MS;
    unsigned long long _blockCount1000MS;
    unsigned long long _totalBlockDuration;
    unsigned long long _maxBlockDuration;
    unsigned long long _lastBlockDuration;
    struct opaqueCMSampleBuffer *_lastSampleBuffer;
    _Bool _isInBackground;
    _Bool _isInitOpenglParam;
    long long _format;
    struct CGSize _bufSize;
    struct CGRect _frameRect;
    float _imageVertices[8];
    const float *_preferredConversion;
    struct CGRect _frame;
    CALayer *_layer;
    UITapGestureRecognizer *_tapGestureRecognizer;
    TXCameraFocusSquare *_focusSquare;
    TXCModule *_module;
    _Bool _mirror;
    _Bool _renderable;
    _Bool _focusable;
    unsigned int _renderBuffer;
    unsigned int _frameBuffer;
    unsigned int _yuvYTexture;
    unsigned int _yuvUTexture;
    unsigned int _yuvVTexture;
    unsigned int _vertexShader;
    unsigned int _fragmentShader;
    unsigned int _programHandle;
    unsigned int _positionSlot;
    unsigned int _texCoordSlot;
    unsigned int _yuvTypeUniform;
    unsigned int _textureUniformY;
    unsigned int _textureUniformU;
    unsigned int _textureUniformV;
    unsigned int _yuvConversionMatrixUniform;
    id <TXIRenderViewDelegate> _delegate;
    id <TXINotifyDelegate> _notifyDelegate;
    long long _renderMode;
    long long _rotation;
    CDUnknownBlockType _layoutSubviewCallBack;
    CAEAGLLayer *_eaglLayer;
    EAGLContext *_curContext;
}

+ (Class)layerClass;
+ (const float *)textureCoordinatesForRotation:(unsigned long long)arg1;
- (void).cxx_destruct;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)awakeFromNib;
- (unsigned long long)calculateRotation;
- (void)calculateVertices;
- (void)clearID;
- (unsigned int)compileShader:(id)arg1 withType:(unsigned int)arg2;
- (void)compileShaders;
- (void)convertYUVToRGBOutput;
@property(retain, nonatomic) EAGLContext *curContext; // @synthesize curContext=_curContext;
- (void)dealloc;
- (void)deallocFocusView;
@property(nonatomic) __weak id <TXIRenderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteTexture;
@property(retain, nonatomic) CAEAGLLayer *eaglLayer; // @synthesize eaglLayer=_eaglLayer;
- (void)focusAtPoint:(struct CGPoint)arg1;
- (void)focusTap:(id)arg1;
@property(nonatomic) _Bool focusable; // @synthesize focusable=_focusable;
@property(nonatomic) unsigned int fragmentShader; // @synthesize fragmentShader=_fragmentShader;
@property(nonatomic) unsigned int frameBuffer; // @synthesize frameBuffer=_frameBuffer;
- (id)getID;
- (id)init;
- (void)initFocusView;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)innerRenderFrame:(struct opaqueCMSampleBuffer *)arg1;
- (void)innerRenderFrame:(char *)arg1 format:(long long)arg2 width:(long long)arg3 height:(long long)arg4;
- (void)innerRenderFrame:(char *)arg1 u:(char *)arg2 v:(char *)arg3 format:(long long)arg4 width:(int)arg5 height:(int)arg6;
- (void)innerRenderTexture:(unsigned int)arg1 width:(long long)arg2 height:(long long)arg3;
@property(copy, nonatomic) CDUnknownBlockType layoutSubviewCallBack; // @synthesize layoutSubviewCallBack=_layoutSubviewCallBack;
- (void)layoutSubviews;
@property(nonatomic) _Bool mirror; // @synthesize mirror=_mirror;
@property(nonatomic) __weak id <TXINotifyDelegate> notifyDelegate; // @synthesize notifyDelegate=_notifyDelegate;
@property(nonatomic) unsigned int positionSlot; // @synthesize positionSlot=_positionSlot;
@property(nonatomic) unsigned int programHandle; // @synthesize programHandle=_programHandle;
- (void)removeFromSuperview;
@property(nonatomic) unsigned int renderBuffer; // @synthesize renderBuffer=_renderBuffer;
- (void)renderFrame:(struct opaqueCMSampleBuffer *)arg1;
- (void)renderFrame:(char *)arg1 format:(long long)arg2 width:(long long)arg3 height:(long long)arg4;
@property(nonatomic) long long renderMode; // @synthesize renderMode=_renderMode;
- (void)renderTexture:(unsigned int)arg1 width:(long long)arg2 height:(long long)arg3;
- (void)renderVFrame:(id)arg1;
@property(nonatomic) _Bool renderable; // @synthesize renderable=_renderable;
- (void)resetStats;
@property(nonatomic) long long rotation; // @synthesize rotation=_rotation;
- (void)sendNotifyEvent:(long long)arg1;
- (void)setID:(id)arg1;
- (_Bool)setStatusValue:(id)arg1 forKey:(long long)arg2;
@property(nonatomic) unsigned int texCoordSlot; // @synthesize texCoordSlot=_texCoordSlot;
@property(nonatomic) unsigned int textureUniformU; // @synthesize textureUniformU=_textureUniformU;
@property(nonatomic) unsigned int textureUniformV; // @synthesize textureUniformV=_textureUniformV;
@property(nonatomic) unsigned int textureUniformY; // @synthesize textureUniformY=_textureUniformY;
@property(nonatomic) unsigned int vertexShader; // @synthesize vertexShader=_vertexShader;
@property(nonatomic) unsigned int yuvConversionMatrixUniform; // @synthesize yuvConversionMatrixUniform=_yuvConversionMatrixUniform;
@property(nonatomic) unsigned int yuvTypeUniform; // @synthesize yuvTypeUniform=_yuvTypeUniform;
@property(nonatomic) unsigned int yuvUTexture; // @synthesize yuvUTexture=_yuvUTexture;
@property(nonatomic) unsigned int yuvVTexture; // @synthesize yuvVTexture=_yuvVTexture;
@property(nonatomic) unsigned int yuvYTexture; // @synthesize yuvYTexture=_yuvYTexture;
- (void)setup;
- (void)setupFrameBuffer;
- (void)setupLayer;
- (void)setupRenderBuffer;
- (void)setupTexture;
- (void)snapshot:(CDUnknownBlockType)arg1;
- (void)statisticFrame;
- (id)statusValueForKey:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

