//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TXCFilter.h"

@interface TXCRGB2YUVOutput : TXCFilter
{
    int widthUniform;
    int heightUniform;
    long long _dataType;
}

@property(nonatomic) long long dataType; // @synthesize dataType=_dataType;
- (void)informTargetsAboutNewFrameAtTime:(CDStruct_1b6d18a9)arg1;
- (id)init;
- (void)newFrameReadyAtTime:(CDStruct_1b6d18a9)arg1 atIndex:(long long)arg2;
- (void)reInitFragment;

@end

