//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TXCModule.h"

#import "TXIAudioPlayDelegate.h"
#import "TXINotifyDelegate.h"
#import "TXIVideoDecoderDelegate.h"
#import "TXIVideoJitterBufferDelegate.h"

@class NSString, TXCAudioPlayer, TXCRenderView, TXCVideoDecoder, TXCVideoJitterBuffer;

@interface TXCRenderAndDec : TXCModule <TXIVideoJitterBufferDelegate, TXIVideoDecoderDelegate, TXIAudioPlayDelegate, TXINotifyDelegate>
{
    struct CGSize _videoSize;
    _Bool _isHevc;
    _Bool _enableMute;
    _Bool _enableRealTimePlay;
    _Bool _enableAutoAdjustCache;
    _Bool _enableAudioHWAcceleration;
    _Bool _enableSortFrame;
    _Bool _enableVideoHWAcceleration;
    _Bool _isPlaying;
    float _cacheTime;
    float _minAutoAdjustCacheTime;
    float _maxAutoAdjustCacheTime;
    id <TXINotifyDelegate> _notifyDelegate;
    id <TXICustomRenderDelegate> _customRenderDelegate;
    long long _rotation;
    long long _renderMode;
    NSString *_audioInfo;
    TXCVideoJitterBuffer *_videoJitterBuffer;
    TXCVideoDecoder *_videoDecoder;
    TXCAudioPlayer *_audioPlayer;
    TXCRenderView *_renderView;
}

+ (void)setAudioMode:(long long)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long audioCacheDuration;
@property(retain, nonatomic) NSString *audioInfo; // @synthesize audioInfo=_audioInfo;
@property(readonly, nonatomic) long long audioJitter;
@property(retain) TXCAudioPlayer *audioPlayer; // @synthesize audioPlayer=_audioPlayer;
@property(readonly, nonatomic) long long avNetRecvInterval;
@property(readonly, nonatomic) long long avPlayInterval;
@property(nonatomic) float cacheTime; // @synthesize cacheTime=_cacheTime;
- (void)createDecoder;
@property(nonatomic) __weak id <TXICustomRenderDelegate> customRenderDelegate; // @synthesize customRenderDelegate=_customRenderDelegate;
- (void)dealloc;
@property(nonatomic) _Bool enableAudioHWAcceleration; // @synthesize enableAudioHWAcceleration=_enableAudioHWAcceleration;
@property(nonatomic) _Bool enableAutoAdjustCache; // @synthesize enableAutoAdjustCache=_enableAutoAdjustCache;
@property(nonatomic) _Bool enableMute; // @synthesize enableMute=_enableMute;
@property(nonatomic) _Bool enableRealTimePlay; // @synthesize enableRealTimePlay=_enableRealTimePlay;
@property(nonatomic) _Bool enableSortFrame; // @synthesize enableSortFrame=_enableSortFrame;
@property(nonatomic) _Bool enableVideoHWAcceleration; // @synthesize enableVideoHWAcceleration=_enableVideoHWAcceleration;
- (id)init;
@property(readonly, nonatomic) _Bool isPlaying; // @synthesize isPlaying=_isPlaying;
@property(nonatomic) float maxAutoAdjustCacheTime; // @synthesize maxAutoAdjustCacheTime=_maxAutoAdjustCacheTime;
@property(nonatomic) float minAutoAdjustCacheTime; // @synthesize minAutoAdjustCacheTime=_minAutoAdjustCacheTime;
@property(nonatomic) __weak id <TXINotifyDelegate> notifyDelegate; // @synthesize notifyDelegate=_notifyDelegate;
- (void)onAppDidBecomeActive:(id)arg1;
- (void)onAppWillResignActive:(id)arg1;
- (void)onDecodeFrame:(struct opaqueCMSampleBuffer *)arg1 FrameType:(long long)arg2 FrameIndex:(unsigned long long)arg3 FramePTS:(unsigned long long)arg4 FrameDTS:(unsigned long long)arg5 ErrorCode:(unsigned long long)arg6;
- (void)onNALAvaliable:(id)arg1;
- (void)onNotifyEvent:(int)arg1 withParams:(id)arg2;
- (void)onPlayAudioInfoChanged:(id)arg1 reasample:(id)arg2;
- (void)onPlayPcmData:(id)arg1;
- (long long)onRequestAudioBufferDuration;
- (int)onRequestVideoDecoderCacheNum;
@property(readonly, nonatomic) float playSpeed;
- (long long)pushAudio:(id)arg1;
- (void)pushNAL:(id)arg1;
- (void)releaseDecoder;
- (void)removeRender;
@property(nonatomic) long long renderMode; // @synthesize renderMode=_renderMode;
- (void)renderToView:(id)arg1 atIndex:(long long)arg2;
@property(retain) TXCRenderView *renderView; // @synthesize renderView=_renderView;
@property(nonatomic) long long rotation; // @synthesize rotation=_rotation;
- (void)setID:(id)arg1;
@property(retain) TXCVideoDecoder *videoDecoder; // @synthesize videoDecoder=_videoDecoder;
@property(retain) TXCVideoJitterBuffer *videoJitterBuffer; // @synthesize videoJitterBuffer=_videoJitterBuffer;
- (void)snapshot:(CDUnknownBlockType)arg1;
- (int)start;
- (void)stop;
- (void)stopKeepLastFrame:(_Bool)arg1;
- (void)updateLoadInfo;
@property(readonly, nonatomic) long long videoCacheDuration;
@property(readonly, nonatomic) long long videoCacheFrameCount;
@property(readonly, nonatomic) long long videoDecCacheFrameCount;
@property(readonly, nonatomic) long long videoGop;
@property(readonly, nonatomic) struct CGSize videoSize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

