//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TXCStatus : NSObject
{
}

+ (_Bool)setValue:(id)arg1 forID:(id)arg2 key:(long long)arg3;
+ (void)startRecord:(id)arg1;
+ (void)stopRecord:(id)arg1;
+ (id)valueForID:(id)arg1 key:(long long)arg2;

@end

