//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>;

@interface TXCVideoJitterBuffer : NSObject
{
    NSMutableArray *_nalArray;
    long long _fps;
    unsigned long long _lastPlayTime;
    long long _totalFPS;
    long long _fpsCount;
    unsigned long long _lastFrameTS;
    NSObject<OS_dispatch_queue> *_workQueue;
    _Bool _working;
    double _interval;
    long long _fixTime;
    long long _cacheTimeMS;
    long long _speedTimeMS;
    int _gopCnt;
    id <TXIVideoJitterBufferDelegate> _delegate;
    long long _bufferFrameCount;
    unsigned long long _curRenderTS;
    unsigned long long _curNetTS;
    long long _gop;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) long long bufferDurationOnTS;
@property(nonatomic) long long bufferFrameCount; // @synthesize bufferFrameCount=_bufferFrameCount;
- (void)calcFPS:(unsigned long long)arg1;
- (void)clear;
@property(readonly, nonatomic) unsigned long long curNetTS; // @synthesize curNetTS=_curNetTS;
@property(readonly, nonatomic) unsigned long long curRenderTS; // @synthesize curRenderTS=_curRenderTS;
@property(nonatomic) __weak id <TXIVideoJitterBufferDelegate> delegate; // @synthesize delegate=_delegate;
- (long long)getVideoFrameRenderInterval;
@property(readonly, nonatomic) long long gop; // @synthesize gop=_gop;
- (id)init;
- (void)notifyRenderTS:(unsigned long long)arg1;
- (id)pullNAL;
- (void)pushNAL:(id)arg1;
- (id)queryNAL;
- (void)scheduleQuery;
- (void)setInterval:(double)arg1;
- (void)start;
- (void)stop;

@end

