//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TXIVideoEncoder;

@interface TXCVideoEncoder : NSObject
{
    _Bool _isRunning;
    int _encoderType;
    TXIVideoEncoder *_videoEncoder;
}

+ (id)encoder:(int)arg1;
- (void).cxx_destruct;
- (void)createEncoderWithType:(int)arg1;
- (void)dealloc;
- (long long)encodeFrameCount;
@property(nonatomic) int encoderType; // @synthesize encoderType=_encoderType;
- (id)initBy:(int)arg1;
@property(nonatomic) _Bool isRunning; // @synthesize isRunning=_isRunning;
- (long long)pushSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 timestamp:(unsigned long long)arg2;
- (long long)realBitrate;
- (long long)realFPS;
- (long long)realGop;
- (void)setBitrate:(long long)arg1;
- (void)setDelegate:(id)arg1;
- (void)setID:(id)arg1;
- (void)setNotifyDelegate:(id)arg1;
@property(retain) TXIVideoEncoder *videoEncoder; // @synthesize videoEncoder=_videoEncoder;
- (long long)startWith:(struct tagTXSVideoEncoderParam *)arg1;
- (long long)stop;

@end

