//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface TXExtInfo : NSObject
{
    _Bool report_common;
    _Bool report_status;
    NSString *url;
    NSString *command_id_comm;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *command_id_comm; // @synthesize command_id_comm;
- (id)init;
@property(nonatomic) _Bool report_common; // @synthesize report_common;
@property(nonatomic) _Bool report_status; // @synthesize report_status;
@property(retain, nonatomic) NSString *url; // @synthesize url;

@end

