//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@protocol TXICustomPreprocessDelegate <NSObject>

@optional
- (unsigned int)onCustomPreprocess:(unsigned int)arg1 width:(long long)arg2 height:(long long)arg3;
- (void)onDetectFacePoints:(NSArray *)arg1;
- (void)onTextureDestoryed;
@end

