//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TXICustomRenderDelegate.h"
#import "TXINotifyDelegate.h"

@class NSString, TXCPlayerConfig, TXIPlayer, TXLivePlayConfig, UITextView, UIView;

@interface TXLivePlayer : NSObject <TXINotifyDelegate, TXICustomRenderDelegate>
{
    TXIPlayer *_player;
    TXCPlayerConfig *_playerConfig;
    UIView *_containView;
    UITextView *_statusView;
    UITextView *_evtLogView;
    unsigned int _insertIndex;
    NSString *_playUrl;
    _Bool _mute;
    int _width;
    int _height;
    _Bool _enableHWAcceleration;
    _Bool _firstPlay;
    id <TXLivePlayListener> _delegate;
    id <TXVideoCustomProcessDelegate> _videoProcessDelegate;
    TXLivePlayConfig *_config;
}

- (void).cxx_destruct;
- (void)applyConfig;
@property(copy, nonatomic) TXLivePlayConfig *config; // @synthesize config=_config;
- (void)dealloc;
@property(nonatomic) __weak id <TXLivePlayListener> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool enableHWAcceleration; // @synthesize enableHWAcceleration=_enableHWAcceleration;
@property _Bool firstPlay; // @synthesize firstPlay=_firstPlay;
- (id)init;
- (_Bool)isPlaying;
- (_Bool)onCustomRender:(struct __CVBuffer *)arg1;
- (void)onNotifyEvent:(int)arg1 withParams:(id)arg2;
- (void)pause;
- (void)removeVideoWidget;
- (void)resume;
- (int)seek:(float)arg1;
- (void)setMute:(_Bool)arg1;
- (void)setRenderMode:(long long)arg1;
- (void)setRenderRotation:(int)arg1;
@property(nonatomic) __weak id <TXVideoCustomProcessDelegate> videoProcessDelegate; // @synthesize videoProcessDelegate=_videoProcessDelegate;
- (void)setupVideoWidget:(struct CGRect)arg1 containView:(id)arg2 insertIndex:(unsigned int)arg3;
- (void)showVideoDebugLog:(_Bool)arg1;
- (void)snapshot:(CDUnknownBlockType)arg1;
- (int)startPlay:(id)arg1 type:(long long)arg2;
- (int)stopPlay;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

