//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_source>, TXAudioBufferQueue;

@interface TXReplayKitMixer : NSObject
{
    TXAudioBufferQueue *_appSamples;
    TXAudioBufferQueue *_micSamples;
    struct AudioStreamBasicDescription _ASBD;
    unsigned long long _maxBufCount;
    _Bool _timeChecked;
    _Bool _packPauseDelay;
    _Bool _hasMicIn;
    _Bool _noMicIn;
    _Bool _noAppIn;
    _Bool _hasAppIn;
    CDStruct_1b6d18a9 _startTime;
    CDStruct_1b6d18a9 _lastSendTime;
    NSObject<OS_dispatch_source> *_audioTimer;
}

- (void).cxx_destruct;
- (void)appendSample:(struct opaqueCMSampleBuffer *)arg1 withType:(long long)arg2;
- (void)clear;
- (struct opaqueCMSampleBuffer *)getSendSampleBuffer:(id)arg1;
- (id)init;
- (void)mixAudioInternal:(char *)arg1 withSrc:(char *)arg2 withLength:(unsigned int)arg3;
- (struct opaqueCMSampleBuffer *)mixSample:(struct opaqueCMSampleBuffer *)arg1 withType:(long long)arg2;
- (void)pause:(CDUnknownBlockType)arg1;
- (void)pickBuffer:(id *)arg1 and:(id *)arg2;
- (void)resume;
- (void)setStartTime:(CDStruct_1b6d18a9)arg1;

@end

