//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebView.h"

@interface UIWebView (AccessoryHiding)
+ (void)setAccessoryView:(id)arg1;
- (_Bool)becomeFirstResponder;
- (_Bool)browserViewBecomeFirstResponder;
- (_Bool)browserViewResignFirstResponder;
- (void)ensureSubclassExistsOfBrowserViewClass:(Class)arg1;
- (id)findAccessoryView;
- (id)findAccessoryView:(id)arg1;
- (id)getAccessoryName;
- (id)getBrowserName;
- (_Bool)hidesInputAccessoryView;
- (id)methodReturningNil;
- (_Bool)mightPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)resignFirstResponder;
- (void)setEnabled:(_Bool)arg1;
- (void)setHidesInputAccessoryView:(_Bool)arg1;
@end

