//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ReaderMessageCellView.h"

@class AsyncImageView, CALayer, UIImageView, UIView, VideoReaderMessageViewModel;

@interface VideoReaderMessageCellView : ReaderMessageCellView
{
    CALayer *m_hightlightLayer;
    AsyncImageView *m_coverImageView;
    UIImageView *m_playBtnView;
    UIView *m_titleTimeView;
}

- (void).cxx_destruct;
- (void)layoutContentView;
- (struct CGRect)previewingSourceRectForLocation:(struct CGPoint)arg1 inCoordinateView:(id)arg2;
- (void)setHighlighted:(_Bool)arg1;
- (id)viewForTitleAndTimeLabel;

// Remaining properties
@property(readonly, nonatomic) VideoReaderMessageViewModel *viewModel; // @dynamic viewModel;

@end

