//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class UIImage;

@interface VideoCompositionAttr : MMObject
{
    UIImage *overlayImage;
    unsigned long long _entranceType;
    CDStruct_e83c9415 cropTimeRange;
}

- (void).cxx_destruct;
@property(nonatomic) CDStruct_e83c9415 cropTimeRange; // @synthesize cropTimeRange;
@property(nonatomic) unsigned long long entranceType; // @synthesize entranceType=_entranceType;
@property(retain, nonatomic) UIImage *overlayImage; // @synthesize overlayImage;

@end

