//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SightPlayerView.h"

#import "VideoStreamPlayerViewModeDelegate.h"

@class NSArray, NSObject, NSString, VideoStreamInfo, VideoStreamKVReportLogic, VideoStreamPlayerViewModel;

@interface VideoStreamPlayerView : SightPlayerView <VideoStreamPlayerViewModeDelegate>
{
    NSObject *m_oPlaybackTimeObserver;
    _Bool m_bBuffering;
    NSArray *m_arrBufferTimes;
    _Bool m_bForcePause;
    unsigned long long m_uLastBufferTime;
    _Bool m_bShouldResumePlayWhenApplicationDidBecomeActive;
    _Bool _bShouldResumeMusicPlayAtPause;
    _Bool _bShouldRetPlayerWhenDownloadSucess;
    _Bool _bHadTryResetPlayerToLocalPlay;
    float _m_uiCurrentPlayedSec;
    VideoStreamKVReportLogic *m_oKVReportLogic;
    VideoStreamInfo *m_oVideoInfo;
    VideoStreamPlayerViewModel *_m_oPlayViewModel;
    id <NSObject><AVPlayerStateControlDelegate> _controlDelegate;
}

- (void).cxx_destruct;
- (void)OnSnsVideoChanged;
- (void)OnVideoDownloadErrorExpired:(_Bool)arg1;
- (void)ShouldUpdateThumbImage:(id)arg1;
- (void)appBecomeActive:(id)arg1;
- (void)appWillResignActive:(id)arg1;
@property(nonatomic) _Bool bHadTryResetPlayerToLocalPlay; // @synthesize bHadTryResetPlayerToLocalPlay=_bHadTryResetPlayerToLocalPlay;
@property(nonatomic) _Bool bShouldResumeMusicPlayAtPause; // @synthesize bShouldResumeMusicPlayAtPause=_bShouldResumeMusicPlayAtPause;
@property(nonatomic) _Bool bShouldRetPlayerWhenDownloadSucess; // @synthesize bShouldRetPlayerWhenDownloadSucess=_bShouldRetPlayerWhenDownloadSucess;
- (id)buildAVItem;
- (void)calculateDataBufferState;
- (void)checkPlayerState;
- (void)clearPlayer;
@property(nonatomic) __weak id <NSObject><AVPlayerStateControlDelegate> controlDelegate; // @synthesize controlDelegate=_controlDelegate;
- (void)dealloc;
- (void)genThumbIfNeed;
- (id)getAVPlayer;
- (id)getAVPlayerItem;
- (id)getFormalVideoPath;
- (double)getVideoBufferedTime;
- (double)getVideoCurrentSeconde;
- (void)initPlayer;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)isStreamingPlayMode;
@property(retain, nonatomic) VideoStreamKVReportLogic *m_oKVReportLogic; // @synthesize m_oKVReportLogic;
@property(retain, nonatomic) VideoStreamPlayerViewModel *m_oPlayViewModel; // @synthesize m_oPlayViewModel=_m_oPlayViewModel;
@property(retain, nonatomic) VideoStreamInfo *m_oVideoInfo; // @synthesize m_oVideoInfo;
@property(nonatomic) float m_uiCurrentPlayedSec; // @synthesize m_uiCurrentPlayedSec=_m_uiCurrentPlayedSec;
- (void)makeSureVideoPauseWhenNextAppActivePlay;
- (void)monitoringPlayback:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onDownloadProgress:(unsigned int)arg1;
- (void)onDownloadSuccess;
- (void)pauseForce:(_Bool)arg1;
- (void)playToEnd:(id)arg1;
- (void)reportKVArgs:(struct C2CDownloadResult)arg1;
- (void)resetPlayerToLocalPlay;
- (void)seekTo:(float)arg1;
- (void)setBufferState:(_Bool)arg1;
- (void)setForcePause:(_Bool)arg1;
- (void)startBuffering;
- (unsigned long long)startDownloadVideo;
- (void)startPlayer;
- (void)stopDownloadVideo;
- (void)tryToBeginPlayVideo;
- (void)tryToPauseAndStartLoading;
- (void)tryToPlayAndStopLoading;
- (void)updateVideoArgs;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

