//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"
#import "VoiceTransDelegate.h"

@class NSMutableArray, NSString, SessionVoiceTranslateInfos, VoiceTransHelper, VoiceTranslateInfo, VoiceTranslateUtil;

@interface VoiceTranslateMsgMgr : MMService <VoiceTransDelegate, MMService>
{
    VoiceTranslateUtil *m_oVoiceTranslateUtil;
    VoiceTranslateInfo *m_oCurrentTranslateInfo;
    VoiceTransHelper *m_oVoiceTransHelper;
    NSMutableArray *m_oTranslateTaskArray;
    SessionVoiceTranslateInfos *m_oSessionTranslateInfo;
}

- (void).cxx_destruct;
- (void)CheckQueue;
- (void)addTranslateInfo:(id)arg1 ChatName:(id)arg2;
- (void)checkSessionInfos:(id)arg1;
- (void)cleanSessionTransInfos:(id)arg1;
- (id)getTranslateInfo:(id)arg1;
- (id)loadSessionTransInfos:(id)arg1;
- (void)onServiceInit;
- (void)onServiceReloadData;
- (void)onVoiceTransBegin:(id)arg1;
- (void)onVoiceTransEnd:(id)arg1 FromCache:(_Bool)arg2;
- (void)onVoiceTransFail:(id)arg1;
- (void)onVoiceTransVoiceID:(id)arg1 Result:(id)arg2;
- (void)removeTranslateInfo:(id)arg1;
- (void)stopAllScrollUp;
- (void)stopVoiceTranslate:(id)arg1;
- (void)translateVoiceMessage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

