//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CommonMessageViewModel.h"

@class NSString, VoiceTranslateInfo;

@interface VoiceMessageViewModel : CommonMessageViewModel
{
    _Bool _isPlaying;
    double _voiceNodeWidth;
    double _voiceNodeHeight;
    VoiceTranslateInfo *_voiceTranslateInfo;
}

+ (_Bool)canCreateMessageViewModelWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (id)additionalAccessibilityDescription;
- (void)adjustTableOffset:(struct CGRect)arg1 delayForReloadTable:(_Bool)arg2;
- (_Bool)canShowTranslateLoadingView;
- (_Bool)canShowTranslateText;
- (id)cellViewClassName;
@property(readonly, nonatomic) struct CGSize displayTextSize;
- (struct CGRect)getCellFrame;
- (id)getDisplayString;
- (_Bool)hasLocalTranslateResult;
@property(nonatomic) _Bool isPlaying; // @synthesize isPlaying=_isPlaying;
- (struct CGSize)measureContentViewSize:(struct CGSize)arg1;
- (void)onMessageStartPlaying;
- (void)onMessageStopPlaying;
- (id)pathOfTranslateResult;
- (void)removeTranslateVoiceInfo;
@property(nonatomic) double voiceNodeHeight; // @synthesize voiceNodeHeight=_voiceNodeHeight;
@property(nonatomic) double voiceNodeWidth; // @synthesize voiceNodeWidth=_voiceNodeWidth;
@property(retain, nonatomic) VoiceTranslateInfo *voiceTranslateInfo; // @synthesize voiceTranslateInfo=_voiceTranslateInfo;
- (void)stopTranslateVoice;
- (void)translateVoice;
@property(readonly, nonatomic) struct CGSize translatedTextSize;
@property(readonly, nonatomic) double voiceTimeLength;
@property(readonly, nonatomic) NSString *voiceTimeStirng;

@end

