//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"
#import "WAAppTaskDelegate.h"

@class MMTimer, NSMutableArray, NSMutableDictionary, NSString, WATopSessionTaskInfoStorage;

@interface WAAppTaskMgr : MMService <WAAppTaskDelegate, MMService>
{
    NSMutableArray *_arrJumpList;
    NSMutableDictionary *_dicAppID2Task;
    MMTimer *_timerCheckBackgroundTask;
    unsigned int lastMemoryWaringTimeStamp;
    NSString *_curBackToChatAppID;
    NSString *_curBackToChatDefaultName;
    WATopSessionTaskInfoStorage *_topSessionTaskInfoStorage;
}

- (void).cxx_destruct;
- (void)addJumpWeAppRelationIfHave:(id)arg1;
- (void)addJumpWeAppRelationWithFromAppId:(id)arg1 toAppId:(id)arg2 jumpScene:(unsigned long long)arg3;
- (void)addNativeJumpWeAppRefererInfoIfHave:(id)arg1 openInfo:(id)arg2 extInfo:(id)arg3;
- (id)allTaskArray;
- (void)checkAndCloseExceedMaxConcurrentCountTask;
- (void)checkGameAppBackgroundTask;
- (void)clearJumpList;
- (void)clearTaskDataAndNotifyTerminate:(id)arg1;
- (void)clearTaskDataAndNotifyTerminate:(id)arg1 isCallCloseTask:(_Bool)arg2;
- (void)closeAllTaskUseTips:(_Bool)arg1;
- (void)closeAllWebViewInNavigatorTask;
- (void)closeBackgroundTask:(_Bool)arg1;
- (void)closeTask:(id)arg1;
- (void)closeTaskWithAppID:(id)arg1;
- (void)closeTimeoutBackgoundTask;
- (void)dealloc;
- (void)deleteTask:(id)arg1;
- (void)generateJumpWeAppOperation:(id *)arg1 withAppId:(id)arg2 extInfo:(id)arg3;
- (id)getAndNewTaskIfNotExistWithAppID:(id)arg1 relativeURL:(id)arg2 taskExtInfo:(id)arg3 debugModeType:(unsigned int)arg4;
- (id)getAppIdListFromJumpWeAppList;
- (unsigned long long)getAppTaskCount;
- (id)getCurrentBackToChatAppId;
- (id)getCurrentBackToChatAppTask;
- (id)getCurrentBackToChatAppTaskBannerLogoUrl;
- (id)getCurrentBackToChatAppTaskBannerText;
- (unsigned long long)getCurrentBackToChatDebugType;
- (id)getCurrentBackToChatRelativePath;
- (id)getCurrentBackToChatStackPaths;
- (id)getForegroundAppID;
- (unsigned long long)getJumpRoleWithAppId:(id)arg1;
- (void)getJumpWeAppLastInfo:(id *)arg1 fromInfo:(id *)arg2 withAppId:(id)arg3;
- (id)getTaskWithAppID:(id)arg1;
- (_Bool)getWeAppTaskInfo:(id)arg1;
- (void)invadateCheckBackgroundTaskTimer;
- (_Bool)isAppTaskBackingToChat:(id)arg1;
- (_Bool)isExistAppInnerAudioPlaying;
- (_Bool)isExistAppLivePushing;
- (_Bool)isExistAppRecording;
- (_Bool)isFormJumpWeAppRingWithFromAppId:(id)arg1 toAppId:(id)arg2;
- (_Bool)isGameBackgroundTaskAllowToClose:(id)arg1;
- (_Bool)isNeedCloseAppTaskToOpenPagePath:(id)arg1 appID:(id)arg2 appType:(unsigned int)arg3;
- (_Bool)isNeedNewTask:(id)arg1 pagePath:(id)arg2 appType:(unsigned int)arg3;
- (_Bool)isReachMaxWebViewDepthWithAppID:(id)arg1;
- (_Bool)isWeAppScreenOn;
- (void)jumpWeAppCateGoryOnServiceClearData;
- (void)jumpWeAppCategoryOnServiceInit;
- (void)jumpWeAppCategoryOnServiceReloadData;
- (id)lastAppIDWithViewController:(id)arg1;
- (void)loadTopSessionTaskInfo;
- (void)markBackToChatWithAppID:(id)arg1 usrName:(id)arg2 relativePath:(id)arg3 debugModeType:(unsigned long long)arg4;
- (unsigned int)maxGameTaskRunningCount;
- (unsigned int)maxTaskRunningCount;
- (void)onApplicationDidReceiveMemoryWarning:(id)arg1;
- (void)onServiceClearData;
- (void)onServiceEnterBackground;
- (void)onServiceInit;
- (void)onServiceReloadData;
- (void)onTimerCheckBackgroundTask:(id)arg1;
- (void)openAppTaskWithContact:(id)arg1 openInfo:(id)arg2 extInfo:(id)arg3 errorHandler:(CDUnknownBlockType)arg4;
- (void)openChildWebViewWithappID:(id)arg1 relativeURL:(id)arg2 childExtraInfo:(id)arg3 fromParent:(id)arg4 isPopAllParent:(_Bool)arg5 errorHandler:(CDUnknownBlockType)arg6;
- (void)openChildWebViewWithappID:(id)arg1 relativeURL:(id)arg2 childExtraInfo:(id)arg3 fromParent:(id)arg4 isPopParent:(_Bool)arg5 errorHandler:(CDUnknownBlockType)arg6;
- (void)processJumpWeAppBeforeOpenTaskWithAppId:(id)arg1 openInfo:(id)arg2 extInfo:(id)arg3 getOperation:(id *)arg4;
- (void)removeCurBackToChatState;
- (void)removeJumpWeAppLastInfo;
- (void)removeTopSesionTaskInfo;
- (void)saveTopSessionTaskInfo:(id)arg1;
- (void)sendJSEventToTaskAllWebView:(id)arg1 withAppID:(id)arg2 param:(id)arg3 toWebviews:(id)arg4;
- (void)startCheckBackgroundTaskTimer;
- (void)taskBackgroundNetworkInterruptedTimeout:(id)arg1;
- (void)taskDidClose:(id)arg1;
- (void)taskDidOpen:(id)arg1;
- (void)taskEnterBackgroundWithAppID:(id)arg1 andRelativePath:(id)arg2;
- (void)updateCurrentBackToChatState;
- (void)updateCurrentBannerText:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

