//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAudioPlayerDelegate.h"
#import "WAAudioSource.h"

@class AVAudioPlayer, NSString;

@interface WAAudioSourceAVAudio : NSObject <AVAudioPlayerDelegate, WAAudioSource>
{
    AVAudioPlayer *_player;
    _Bool _isForcePause;
    double _forcePausedPosition;
    _Bool _obeyMuteSwitch;
    _Bool _loop;
    float _duration;
    long long _state;
    NSString *_path;
    NSString *_audioId;
    id <WAAudioSourceDelegate> _delegate;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *audioId; // @synthesize audioId=_audioId;
- (void)audioPlayerDecodeErrorDidOccur:(id)arg1 error:(id)arg2;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
@property(nonatomic) float currentTime;
- (void)dealloc;
@property(nonatomic) __weak id <WAAudioSourceDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) float duration; // @synthesize duration=_duration;
- (void)forcePause;
- (id)initWithPath:(id)arg1 filData:(id)arg2;
- (_Bool)isPaused;
- (_Bool)isPlaying;
@property(nonatomic) _Bool loop; // @synthesize loop=_loop;
@property(nonatomic) _Bool obeyMuteSwitch; // @synthesize obeyMuteSwitch=_obeyMuteSwitch;
@property(retain, nonatomic) NSString *path; // @synthesize path=_path;
- (void)pause;
- (void)play;
- (void)seek:(double)arg1;
- (void)setLooping:(_Bool)arg1;
- (void)setPlaybackRate:(float)arg1;
@property(nonatomic) long long state; // @synthesize state=_state;
- (void)setVolume:(float)arg1;
- (void)stop;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

