//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureMetadataOutputObjectsDelegate.h"
#import "GPUImageVideoCameraDelegate.h"
#import "MMovieCompressorDelegate.h"
#import "UIAlertViewDelegate.h"
#import "WCCameraPreviewDelegate.h"
#import "WCCameraWriterDelegate.h"

@class GPUImageCropFilter, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, UIImage, WAFilterLogic, WCCameraCapture, WCCameraPreview;

@interface WACameraLogicController : NSObject <UIAlertViewDelegate, MMovieCompressorDelegate, WCCameraWriterDelegate, WCCameraPreviewDelegate, AVCaptureMetadataOutputObjectsDelegate, GPUImageVideoCameraDelegate>
{
    WCCameraPreview *_cameraPreview;
    WAFilterLogic *_filterLogic;
    GPUImageCropFilter *_cropFilter;
    NSMutableArray *m_compressorAry;
    unsigned int m_currID;
    NSObject<OS_dispatch_queue> *m_logicQueue;
    NSMutableArray *m_recordIDAry;
    unsigned int m_currWriterID;
    long long m_currentOrientation;
    _Bool isShowingPreview;
    _Bool isCameraAppear;
    _Bool bNeedOutputVideoBuffer;
    _Bool _m_isTakingPicture;
    _Bool _m_shouldStart;
    _Bool _m_requestAuthAccess;
    int _recordState;
    id <WACameraLogicControllerDelegate> _delegate;
    WCCameraCapture *_cameraCapture;
    NSString *_m_videoPath;
    UIImage *_m_thumbImage;
    UIImage *_m_originalImage;
    NSMutableDictionary *_recorderDict;
}

+ (_Bool)isAuthStatusOK;
+ (_Bool)needCheckRequestAuthAccess;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(nonatomic) _Bool bNeedOutputVideoBuffer; // @synthesize bNeedOutputVideoBuffer;
@property(retain, nonatomic) WCCameraCapture *cameraCapture; // @synthesize cameraCapture=_cameraCapture;
- (void)cameraViewControllerDidRotate:(id)arg1;
- (void)cancelAllRecorder;
- (void)cancelRecording:(unsigned int)arg1;
- (void)cancelWriter;
- (void)cancelWriterWithoutReprepare;
- (void)dealloc;
@property(nonatomic) __weak id <WACameraLogicControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didEnterBackground;
- (void)didEnterForeground;
- (void)didTakeDoneWithPicture:(id)arg1;
- (void)didTakeDoneWithSightPath:(id)arg1 thumbImg:(id)arg2 isMuted:(_Bool)arg3;
- (void)didTapRetake;
- (void)filterType:(unsigned long long)arg1;
- (_Bool)finishWriter;
- (void)focusAtPoint:(struct CGPoint)arg1;
- (id)genPreviewView:(struct CGRect)arg1;
- (id)init;
@property(nonatomic) _Bool isCameraAppear; // @synthesize isCameraAppear;
- (_Bool)isRecording:(unsigned int)arg1;
@property(nonatomic) _Bool isShowingPreview; // @synthesize isShowingPreview;
- (_Bool)isSupportZoomWithFactor:(double)arg1;
- (void)loadCameraLogicWithContentView:(id)arg1;
- (void)mMovieCompressor:(id)arg1 onMovieCompressFinished:(id)arg2 thumbImg:(id)arg3 ret:(unsigned int)arg4;
@property(nonatomic) _Bool m_isTakingPicture; // @synthesize m_isTakingPicture=_m_isTakingPicture;
@property(retain, nonatomic) UIImage *m_originalImage; // @synthesize m_originalImage=_m_originalImage;
@property(nonatomic) _Bool m_requestAuthAccess; // @synthesize m_requestAuthAccess=_m_requestAuthAccess;
@property(nonatomic) _Bool m_shouldStart; // @synthesize m_shouldStart=_m_shouldStart;
@property(retain, nonatomic) UIImage *m_thumbImage; // @synthesize m_thumbImage=_m_thumbImage;
@property(retain, nonatomic) NSString *m_videoPath; // @synthesize m_videoPath=_m_videoPath;
- (void)movieWriter:(id)arg1 onMovieWriteFailed:(unsigned int)arg2;
- (void)movieWriter:(id)arg1 onMovieWriteFinished:(id)arg2 ret:(unsigned int)arg3;
- (void)onCameraStop:(id)arg1;
- (void)onMovieCompressFinished:(int)arg1 moviePath:(id)arg2 withThumb:(id)arg3;
- (void)onMovieWriterInvalidate:(id)arg1;
- (void)onTakenPicture:(id)arg1;
- (void)onWriterFailed:(int)arg1;
- (void)onWriterResign;
- (void)pauseCamera;
@property(nonatomic) int recordState; // @synthesize recordState=_recordState;
@property(retain, nonatomic) NSMutableDictionary *recorderDict; // @synthesize recorderDict=_recorderDict;
- (void)removeCameraCropFilter;
- (void)resumeCamera;
- (void)setCameraCropRect:(struct CGRect)arg1;
- (void)setCameraPositon:(long long)arg1;
- (void)setFlashType:(long long)arg1;
- (void)showPreviewViewWithImage:(id)arg1;
- (void)showPreviewViewWithSightPath:(id)arg1 thumbImg:(id)arg2;
- (float)sightCaptureMaxDuration;
- (_Bool)startRecord;
- (unsigned int)startRecord:(struct CGSize)arg1 bitRate:(int)arg2 needCompress:(_Bool)arg3 maxVideoDuration:(float)arg4 orientation:(long long)arg5 compressAudio:(_Bool)arg6 audioBitrate:(float)arg7;
- (_Bool)startWriter;
- (_Bool)stopRecord;
- (void)stopRecording:(unsigned int)arg1;
- (void)switchCamera;
- (_Bool)takePicture;
- (void)updateCameraPreviewRect:(struct CGRect)arg1;
- (void)willOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)zoomFactor:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

