//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMDBRRepairerExt.h"
#import "MMService.h"

@class NSString, WCTDatabase, WCTTable;

@interface WADatabaseMgr : MMService <MMDBRRepairerExt, MMService>
{
    WCTDatabase *_db;
    WCTTable *_tableWeAppInfo;
    WCTTable *_tableWeAppModuleInfo;
    WCTTable *_tablePermissionInfo;
    WCTTable *_tableContact;
    WCTTable *_tableBizAttrSyncBuffer;
    WCTTable *_tableConfigInfo;
    WCTTable *_tableWeAppListItem;
    WCTTable *_tableWeAppStarItem;
    WCTTable *_tableMainFrameTaskItem;
}

+ (_Bool)deleteInfoDataWithTable:(id)arg1 where:(const struct WCTExpr *)arg2;
+ (id)getInfoDataWithTable:(id)arg1 primaryKey:(id)arg2;
+ (_Bool)insertOrUpdateInfoDataWithTable:(id)arg1 infoData:(id)arg2;
- (void).cxx_destruct;
- (id)appIdPrimaryKeyWithAppId:(id)arg1 moduleName:(id)arg2;
- (_Bool)clearBizAttrSyncBufferList:(id)arg1;
- (void)closeDB;
- (id)contactFromDBContact:(id)arg1;
@property(retain) WCTDatabase *db; // @synthesize db=_db;
- (id)dbContactWithContact:(id)arg1;
- (id)dbPath;
- (void)dealloc;
- (_Bool)deleteAllAppListItem;
- (_Bool)deleteAllAppStarItem;
- (_Bool)deleteAppInfoByAppID:(id)arg1;
- (_Bool)deleteAppListItemByUsrName:(id)arg1 appType:(unsigned int)arg2;
- (_Bool)deleteAppModuleInfoByAppID:(id)arg1;
- (_Bool)deleteAppStarItemByUsrName:(id)arg1 appType:(unsigned int)arg2;
- (_Bool)deleteConfigInfoByAppID:(id)arg1;
- (_Bool)deleteContactList:(id)arg1;
- (_Bool)deleteMainFrameTaskItemBeforeUpdateTime:(unsigned int)arg1;
- (_Bool)deleteMainFrameTaskItemWithUserName:(id)arg1 debugMode:(unsigned int)arg2;
- (id)getAllAppListItem;
- (id)getAllAppListItemByUsername:(id)arg1;
- (id)getAllAppListItemOrderByUpdateTime;
- (id)getAllAppListItemOrderByUpdateTimeIsIncludeStar:(_Bool)arg1;
- (id)getAllAppStarItem;
- (id)getAllAppStarItemByUsername:(id)arg1;
- (id)getAllAppStarItemOrderByUpdateTime;
- (id)getAllContact;
- (id)getAllFocusContact;
- (id)getAllNoFocusContact;
- (id)getAppInfoByAppID:(id)arg1;
- (id)getAppListItemByUsername:(id)arg1 appType:(unsigned int)arg2;
- (unsigned int)getAppListItemCount;
- (id)getAppModuleInfoByAppID:(id)arg1 moduleName:(id)arg2;
- (id)getAppStarItemByUsername:(id)arg1 appType:(unsigned int)arg2;
- (unsigned int)getAppStartItemCount;
- (id)getBizAttrSyncBuffer:(id)arg1;
- (id)getConfigInfoByAppID:(id)arg1 andType:(unsigned int)arg2;
- (id)getContact:(id)arg1;
- (id)getContactWithAppId:(id)arg1;
- (id)getContactWithKey:(id)arg1 type:(unsigned long long)arg2;
- (id)getCurrentAppListItemByLimit:(int)arg1;
- (id)getLatestAppListItemOverUpdateTime:(unsigned int)arg1;
- (id)getLatestAppListItemOverUpdateTime:(unsigned int)arg1 includeStar:(_Bool)arg2;
- (id)getLatestAppListItemWithCount:(unsigned int)arg1;
- (id)getLatestAppListItemWithCount:(unsigned int)arg1 includeStar:(_Bool)arg2;
- (id)getLatestAppListItemWithMaxUpdateTime:(unsigned int)arg1 minUpdateTime:(unsigned int)arg2;
- (id)getLatestAppListItemWithMaxUpdateTime:(unsigned int)arg1 minUpdateTime:(unsigned int)arg2 includeStar:(_Bool)arg3;
- (id)getMainFrameTaskItemListWithLimit:(unsigned int)arg1;
- (id)getMainFrameTaskItemListWithLimit:(unsigned int)arg1 ignoreUsername:(id)arg2 debugMode:(unsigned int)arg3;
- (id)getPermissionInfoWithAppID:(id)arg1;
- (id)init;
- (_Bool)inserOrUpdateContactList:(id)arg1;
- (_Bool)insertAppStarItemList:(id)arg1;
- (_Bool)insertOrUpdateAppInfo:(id)arg1;
- (_Bool)insertOrUpdateAppListItem:(id)arg1;
- (_Bool)insertOrUpdateAppModuleInfo:(id)arg1;
- (_Bool)insertOrUpdateAppStarItem:(id)arg1;
- (_Bool)insertOrUpdateConfigInfo:(id)arg1;
- (_Bool)insertOrUpdateMainFrameTaskItem:(id)arg1;
- (_Bool)isItemStared:(id)arg1;
- (_Bool)mergeAppListItems:(id)arg1 updateTimeOfLastItemAfterMerge:(unsigned int *)arg2;
- (_Bool)mergeAppStarItems:(id)arg1;
- (_Bool)modifyHeadImageStatus:(id)arg1 withUserName:(id)arg2;
- (_Bool)modifyWxAppOpt:(id)arg1 bitMask:(unsigned int)arg2 bitValue:(unsigned int)arg3;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)onServiceReloadData;
- (void)openDB;
- (_Bool)setBizAttrSyncBufferList:(id)arg1;
- (_Bool)setPermissionInfo:(id)arg1;
@property(retain) WCTTable *tableBizAttrSyncBuffer; // @synthesize tableBizAttrSyncBuffer=_tableBizAttrSyncBuffer;
@property(retain) WCTTable *tableConfigInfo; // @synthesize tableConfigInfo=_tableConfigInfo;
@property(retain) WCTTable *tableContact; // @synthesize tableContact=_tableContact;
@property(retain) WCTTable *tableMainFrameTaskItem; // @synthesize tableMainFrameTaskItem=_tableMainFrameTaskItem;
@property(retain) WCTTable *tablePermissionInfo; // @synthesize tablePermissionInfo=_tablePermissionInfo;
@property(retain) WCTTable *tableWeAppInfo; // @synthesize tableWeAppInfo=_tableWeAppInfo;
@property(retain) WCTTable *tableWeAppListItem; // @synthesize tableWeAppListItem=_tableWeAppListItem;
@property(retain) WCTTable *tableWeAppModuleInfo; // @synthesize tableWeAppModuleInfo=_tableWeAppModuleInfo;
@property(retain) WCTTable *tableWeAppStarItem; // @synthesize tableWeAppStarItem=_tableWeAppStarItem;
- (id)setupTableWithName:(id)arg1 tableClass:(Class)arg2;
- (_Bool)updateAppListItemOnStarState:(id)arg1;
- (_Bool)updateAppListItemOnUpdateTime:(id)arg1;
- (void)willRepairDB:(unsigned int)arg1 needCatch:(_Bool *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

