//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WAInfoData;

@interface WADownloadInfo : NSObject
{
    _Bool _isUpdateCompleteWithPatch;
    unsigned int _oldVersion;
    unsigned int _targetVersion;
    unsigned int _fullPkgSize;
    unsigned int _patchSize;
    NSString *_fullPkgUrl;
    NSString *_patchPkgUrl;
    double _beginTime;
    WAInfoData *_appInfoData;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WAInfoData *appInfoData; // @synthesize appInfoData=_appInfoData;
@property(nonatomic) double beginTime; // @synthesize beginTime=_beginTime;
@property(nonatomic) unsigned int fullPkgSize; // @synthesize fullPkgSize=_fullPkgSize;
@property(retain, nonatomic) NSString *fullPkgUrl; // @synthesize fullPkgUrl=_fullPkgUrl;
@property(nonatomic) _Bool isUpdateCompleteWithPatch; // @synthesize isUpdateCompleteWithPatch=_isUpdateCompleteWithPatch;
- (_Bool)isUrlEqualPatchUrl:(id)arg1;
@property(nonatomic) unsigned int oldVersion; // @synthesize oldVersion=_oldVersion;
@property(retain, nonatomic) NSString *patchPkgUrl; // @synthesize patchPkgUrl=_patchPkgUrl;
@property(nonatomic) unsigned int patchSize; // @synthesize patchSize=_patchSize;
@property(nonatomic) unsigned int targetVersion; // @synthesize targetVersion=_targetVersion;

@end

