//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WALoadingViewController.h"

#import "IWALocalCacheMgrExt.h"

@class UIButton, UIImageView, UILabel;

@interface WAGameWhatsNewLoadingViewController : WALoadingViewController <IWALocalCacheMgrExt>
{
    long long _progress;
    _Bool _hasClickEnterWeAppBtn;
    _Bool _hasClickSkipBtn;
    _Bool _hasDownload;
    id <WAGameWhatsNewLoadingViewControllerDelegate> _whatsNewDelegate;
    UIImageView *_bootImageView;
    UILabel *_sloganLabel;
    UILabel *_processLabel;
    UIButton *_skipButton;
    UIImageView *_skipArrow;
    UIButton *_EnterWeAppButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *EnterWeAppButton; // @synthesize EnterWeAppButton=_EnterWeAppButton;
@property(retain, nonatomic) UIImageView *bootImageView; // @synthesize bootImageView=_bootImageView;
- (void)dealloc;
@property(nonatomic) _Bool hasClickEnterWeAppBtn; // @synthesize hasClickEnterWeAppBtn=_hasClickEnterWeAppBtn;
@property(nonatomic) _Bool hasClickSkipBtn; // @synthesize hasClickSkipBtn=_hasClickSkipBtn;
@property(nonatomic) _Bool hasDownload; // @synthesize hasDownload=_hasDownload;
- (void)onCheckLocalPkg:(_Bool)arg1;
- (void)onClickEnterWeAppButton:(id)arg1;
- (void)onClickSkipButton:(id)arg1;
- (void)onUpdateAppPkgComplete:(_Bool)arg1 withAppInfoData:(id)arg2 errorCode:(unsigned int)arg3 errorMsg:(id)arg4;
- (void)onUpdateAppPkgProgress:(float)arg1 remainingTime:(unsigned long long)arg2 withAppInfoData:(id)arg3;
- (void)onUpdateFakeProgess:(id)arg1;
@property(retain, nonatomic) UILabel *processLabel; // @synthesize processLabel=_processLabel;
- (void)setProcessValue:(double)arg1;
@property(retain, nonatomic) UIImageView *skipArrow; // @synthesize skipArrow=_skipArrow;
@property(retain, nonatomic) UIButton *skipButton; // @synthesize skipButton=_skipButton;
@property(retain, nonatomic) UILabel *sloganLabel; // @synthesize sloganLabel=_sloganLabel;
@property(nonatomic) __weak id <WAGameWhatsNewLoadingViewControllerDelegate> whatsNewDelegate; // @synthesize whatsNewDelegate=_whatsNewDelegate;
- (void)setupUI;
- (void)startAnimation;
- (void)startEnterAppAnimation;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;

@end

