//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAWebViewController.h"

#import "IVOIPUILogicMgrExt.h"
#import "MMTipsViewControllerDelegate.h"
#import "MultiTalkMgrExt.h"
#import "PBMessageObserverDelegate.h"
#import "WAGameActionSheetDelegate.h"
#import "WAOpenGLViewDelegate.h"
#import "YYWebViewDelegate.h"

@class MMUIButton, MMUIView, NSMutableArray, NSString, NSURLRequest, RCDraggableButton, UILabel, UILongPressGestureRecognizer, UIView, WAGameActionSheet, WAOpenGLView, WAPopOverTaskBarlogic, WAPopOverView, YYWAWebView;

@interface WAGameViewController : WAWebViewController <WAGameActionSheetDelegate, MMTipsViewControllerDelegate, PBMessageObserverDelegate, IVOIPUILogicMgrExt, MultiTalkMgrExt, WAOpenGLViewDelegate, YYWebViewDelegate>
{
    WAOpenGLView *_glView;
    WAGameActionSheet *_gameSheet;
    RCDraggableButton *_debugBtn;
    YYWAWebView *_debugWebView;
    _Bool _vConsoleVisible;
    NSMutableArray *_menuList;
    UIView *_backgroundView;
    UILabel *_fps;
    UILabel *_drawCall;
    UILabel *_triangle;
    UILabel *_vertex;
    _Bool _showStatusBar;
    _Bool _useDebug;
    _Bool _vConsoleFnishLoad;
    NSMutableArray *_logs;
    _Bool _reportPerformance;
    long long _reportPerformanceInterval;
    UILongPressGestureRecognizer *_moreLongPressRecognizer;
    _Bool _isTrigerMoreLongPress;
    UILongPressGestureRecognizer *_exitlongPressRecognizer;
    WAPopOverTaskBarlogic *_popOverLogic;
    WAPopOverView *_popOverView;
    long long _orientation;
    UIView *_inputBackground;
    id <WAGameKeyboardDelegate> _keyboardDelegate;
    unsigned long long _lockedOrientation;
    MMUIView *_capsuleView;
    MMUIButton *_menuMoreButton;
    MMUIButton *_menuExitButton;
}

+ (id)createLoadingView:(id)arg1 inView:(id)arg2 forcePortrait:(_Bool)arg3;
+ (id)createWhatsNewLoadingView:(id)arg1 inView:(id)arg2 whatsNewInfo:(id)arg3;
+ (void)updateLoadingView:(id)arg1 inView:(id)arg2;
- (void).cxx_destruct;
- (void)DismissMyselfAnimated:(_Bool)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)applicationWillTerminate:(id)arg1;
@property(retain, nonatomic) MMUIView *capsuleView; // @synthesize capsuleView=_capsuleView;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)gameActionSheet:(id)arg1 clickedButtonTitle:(id)arg2;
- (void)gameActionSheet:(id)arg1 didDismissWithMenuIndex:(long long)arg2;
- (void)gameActionSheetDidDismiss:(id)arg1;
- (void)gameActionSheetInfoCliked:(id)arg1;
- (id)getAppLaunchConfig;
- (id)getCanvasImage:(unsigned int)arg1;
- (long long)getConfirmButton:(id)arg1;
- (id)getFileData:(id)arg1;
- (id)getMenuButton;
- (id)getWxAppInfoJSON;
- (void)handleEvent:(long long)arg1 userInfo:(id)arg2;
- (void)hideKeyboard;
- (void)hideShowVConsole;
- (void)initOpenGLView:(id)arg1;
- (id)initWithBaseURL:(id)arg1 query:(id)arg2 extraInfo:(id)arg3 delegate:(id)arg4;
- (void)injectGameScript:(id)arg1;
@property(retain, nonatomic) UIView *inputBackground; // @synthesize inputBackground=_inputBackground;
- (unsigned int)insertChildView:(id)arg1 viewId:(unsigned int)arg2 parentId:(unsigned int)arg3;
- (void)insertSubView:(id)arg1;
- (void)internalInitWithBaseURL:(id)arg1 query:(id)arg2 extraInfo:(id)arg3 delegate:(id)arg4;
- (_Bool)isFileExist:(id)arg1;
- (_Bool)isIndexDataLoaded;
- (_Bool)isOrientationLanscape;
@property(nonatomic) __weak id <WAGameKeyboardDelegate> keyboardDelegate; // @synthesize keyboardDelegate=_keyboardDelegate;
- (void)keyboardDidHideNotification:(id)arg1;
- (void)keyboardDidShowNotification:(id)arg1;
- (void)keyboardWillHideNotification:(id)arg1;
- (void)keyboardWillShowNotification:(id)arg1;
- (void)lockOrientation:(long long)arg1;
@property(nonatomic) unsigned long long lockedOrientation; // @synthesize lockedOrientation=_lockedOrientation;
- (void)log:(id)arg1 func:(const char *)arg2 line:(int)arg3;
- (void)logError:(id)arg1 desc:(id)arg2 stack:(id)arg3;
- (id)menuDebugButtonTitleArray;
@property(retain, nonatomic) MMUIButton *menuExitButton; // @synthesize menuExitButton=_menuExitButton;
@property(retain, nonatomic) MMUIButton *menuMoreButton; // @synthesize menuMoreButton=_menuMoreButton;
- (id)menubuttonTitleArray;
- (void)onBeginMultiTalk;
- (void)onClickTipsBtn:(id)arg1 Index:(long long)arg2 tipTag:(long long)arg3;
- (void)onConfirm;
- (void)onLeave:(id)arg1;
- (void)onLongPressExitItem:(id)arg1;
- (void)onLongPressMoreItem:(id)arg1;
- (void)onMenu:(id)arg1;
- (void)onMenuShow;
- (void)onMultiTalkMaximized;
- (void)onMultiTalkMgrBeginToCleanStatus;
- (void)onMultiTalkMinimized;
- (_Bool)onReturn:(id)arg1;
- (void)onSwitchVConsole;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (void)onVideoVoipViewDisappear;
- (void)onVoipMaximized;
- (void)onVoipMinimized;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
- (id)pluginNavBar;
- (id)pluginNavBar;
- (id)pluginReportPageEvent;
- (void)reportGamePerformanceInfo;
- (void)requestGameMenuList;
- (void)resetSubviews;
- (void)restorePortraitOrientationIfNeeded;
- (void)setDeviceOrientation:(_Bool)arg1;
- (void)setFocus:(id)arg1;
- (void)setFullScreen:(_Bool)arg1;
- (void)setTitleInterfaceOritation:(long long)arg1;
- (void)shareGame;
- (_Bool)shouldAutorotate;
- (_Bool)showKeyboard:(id)arg1 delegate:(id)arg2;
- (void)showTipsViewWithTitle:(id)arg1 content:(id)arg2 tipsTag:(long long)arg3 delegate:(id)arg4;
- (void)stop;
- (unsigned long long)supportedInterfaceOrientations;
- (void)systemLog:(id)arg1;
- (void)textInputDidChange:(id)arg1;
- (void)unlockOrientation;
- (void)updatePerf;
- (_Bool)useTransparentNavibar;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)webViewDidFinishLoad:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSURLRequest *request;
@property(readonly) Class superclass;

@end

