//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WALoadingViewController.h"

#import "IWALocalCacheMgrExt.h"

@class UILabel, UIView;

@interface WAGameLoadingViewController : WALoadingViewController <IWALocalCacheMgrExt>
{
    UIView *_fakeNavBar;
    UIView *_backgroundView;
    UILabel *_progressLabel;
    UIView *m_menuView;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)initRightMenu;
- (id)initWithContact:(id)arg1 pagePath:(id)arg2;
- (void)onUpdateAppPkgProgress:(float)arg1 remainingTime:(unsigned long long)arg2 withAppInfoData:(id)arg3;
- (void)startEnterAppAnimation;
- (void)updateContact:(id)arg1;
- (void)useExitLeftNavigationItem;
- (void)viewDidLayoutSubviews;

@end

