//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSArray, NSString, WAGameInfo;

@interface WAGameEntryInfo : MMObject
{
    _Bool _disappearOneClick;
    unsigned int _actionCode;
    NSArray *_previewGameInfos;
    WAGameInfo *_gameCenterWeappInfo;
    NSString *_gameCenterH5String;
    NSString *_noticeWording;
    NSString *_noticeWordingBgColor;
    NSString *_entryWording;
    NSString *_entryWordingColor;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int actionCode; // @synthesize actionCode=_actionCode;
@property(nonatomic) _Bool disappearOneClick; // @synthesize disappearOneClick=_disappearOneClick;
@property(copy, nonatomic) NSString *entryWording; // @synthesize entryWording=_entryWording;
@property(copy, nonatomic) NSString *entryWordingColor; // @synthesize entryWordingColor=_entryWordingColor;
@property(copy, nonatomic) NSString *gameCenterH5String; // @synthesize gameCenterH5String=_gameCenterH5String;
@property(retain, nonatomic) WAGameInfo *gameCenterWeappInfo; // @synthesize gameCenterWeappInfo=_gameCenterWeappInfo;
@property(copy, nonatomic) NSString *noticeWording; // @synthesize noticeWording=_noticeWording;
@property(copy, nonatomic) NSString *noticeWordingBgColor; // @synthesize noticeWordingBgColor=_noticeWordingBgColor;
@property(retain, nonatomic) NSArray *previewGameInfos; // @synthesize previewGameInfos=_previewGameInfos;

@end

