//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

#import "ABNewPersonViewControllerDelegate.h"
#import "ABPeoplePickerNavigationControllerDelegate.h"
#import "CNContactPickerDelegate.h"
#import "CNContactViewControllerDelegate.h"
#import "WCActionSheetDelegate.h"

@class NSDictionary, NSString;

@interface WAJSEventHandler_addPhoneContact : WAJSEventHandler_BaseEvent <WCActionSheetDelegate, CNContactViewControllerDelegate, CNContactPickerDelegate, ABPeoplePickerNavigationControllerDelegate, ABNewPersonViewControllerDelegate>
{
    NSDictionary *_contact;
}

- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)addToExistContact;
@property(retain, nonatomic) NSDictionary *contact; // @synthesize contact=_contact;
- (void)contactPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)contactPickerDidCancel:(id)arg1;
- (void)contactViewController:(id)arg1 didCompleteWithContact:(id)arg2;
- (void)copyToContact:(id)arg1;
- (void)copyToRecord:(void *)arg1;
- (void)createNewContact;
- (void)handleJSEvent:(id)arg1;
- (void)newPersonViewController:(id)arg1 didCompleteWithNewPerson:(const void *)arg2;
- (void)onCancel:(id)arg1;
- (void)openNewPersonViewController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2;
- (void)peoplePickerNavigationController:(id)arg1 didSelectPerson:(void *)arg2;
- (void)peoplePickerNavigationController:(id)arg1 didSelectPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (_Bool)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2;
- (_Bool)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (void)peoplePickerNavigationControllerDidCancel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

