//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

#import "PBMessageObserverDelegate.h"

@interface WAJSEventHandler_openWeRunSetting : WAJSEventHandler_BaseEvent <PBMessageObserverDelegate>
{
    _Bool _bIsNotCheckDeviceNotSupport;
}

- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)dealloc;
- (void)handleJSEvent:(id)arg1;
- (void)tryOpenSetting;

@end

