//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAJSNativeBufferBase.h"

@class JSContext, NSObject<OS_dispatch_queue>, WAJSCoreService;

@interface WAJSWorkFlow : WAJSNativeBufferBase
{
    unsigned int _workerId;
    WAJSCoreService *_service;
    NSObject<OS_dispatch_queue> *_workerQueue;
    JSContext *_context;
}

- (void).cxx_destruct;
@property(retain, nonatomic) JSContext *context; // @synthesize context=_context;
- (id)init:(id)arg1 workerId:(unsigned int)arg2 service:(id)arg3;
- (void)initJSContext:(id)arg1;
- (void)sendErrorEvent:(id)arg1 stack:(id)arg2;
- (void)sendMessage:(id)arg1;
@property(nonatomic) __weak WAJSCoreService *service; // @synthesize service=_service;
@property(nonatomic) unsigned int workerId; // @synthesize workerId=_workerId;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workerQueue; // @synthesize workerQueue=_workerQueue;
- (void)stopWorker;

@end

