//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAJSContextPluginBase.h"

#import "ISysCallCheckExt.h"
#import "IWAAudioPlayerDelegate.h"
#import "MonoServiceLogicExt.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface WAJSContextPlugin_AudioPlayer : WAJSContextPluginBase <IWAAudioPlayerDelegate, ISysCallCheckExt, MonoServiceLogicExt>
{
    struct ALCcontext_struct *_alcContext;
    NSObject<OS_dispatch_queue> *_backgroundQueue;
    _Bool _interuptExternalMusic;
    id <IJSContextPluginDelegate> _resultDelegate;
    NSMutableDictionary *_playerDic;
}

- (void).cxx_destruct;
- (void)BeginInterruption;
- (void)EndInterruption;
- (id)audioCachePathByfileName:(id)arg1;
- (id)audioCacheRootPath;
- (id)createAudioInstance;
- (void)dealloc;
- (void)delayUnActiveAudioSession;
- (void)destoryPlayer:(id)arg1;
- (void)forcePauseAllPlayer;
- (id)getBackgroundQueue;
- (double)getPlayerBufferTime:(id)arg1;
- (double)getPlayerCurtime:(id)arg1;
- (double)getPlayerDuration:(id)arg1;
- (id)getPlayerSrc:(id)arg1;
- (double)getPlayerStartTime:(id)arg1;
- (id)getPlayerWithAudioId:(id)arg1;
- (_Bool)handleEvent:(long long)arg1 userInfo:(id)arg2;
- (id)init;
- (void)interruptAudio;
- (_Bool)isAudioPlayerExist:(id)arg1;
- (_Bool)isPlayerIdle:(id)arg1;
- (_Bool)isPlayerPaused:(id)arg1;
- (_Bool)isPlayerPlaying:(id)arg1;
- (_Bool)isPlayerSet:(id)arg1;
- (_Bool)isPlayerWaiting:(id)arg1;
- (_Bool)isPlayingAudio;
- (id)localPathByAudioData:(id)arg1 pathExtension:(id)arg2;
- (void)onMonoServiceDidEnd;
- (void)onMonoServiceMultitalkWillStart;
- (void)onMonoServiceVoipWillStart;
- (void)onMonoServiceWalkieTalkieWillStart;
- (void)onPlayerStateChange:(long long)arg1 audioId:(id)arg2 errCode:(long long)arg3 errMsg:(id)arg4;
- (void)pausePlayer:(id)arg1;
- (void)playPlayer:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *playerDic; // @synthesize playerDic=_playerDic;
@property(nonatomic) __weak id <IJSContextPluginDelegate> resultDelegate; // @synthesize resultDelegate=_resultDelegate;
- (void)resumeAudioContext;
- (void)seekPlayer:(id)arg1 seekTime:(float)arg2;
- (void)setCurrentContext;
- (void)setPlayerState:(id)arg1 src:(id)arg2 startTime:(double)arg3 autoPlay:(_Bool)arg4 loop:(_Bool)arg5 obeyMuteSwitch:(_Bool)arg6;
- (void)stopAllPlayer;
- (void)stopPlayer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

