//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

#import "PBMessageObserverDelegate.h"

@class NSString;

@interface WAJSEventHandler_launchApplication : WAJSEventHandler_BaseEvent <PBMessageObserverDelegate>
{
    NSString *_appID;
    NSString *_launchAppID;
    NSString *_messageExt;
    NSString *_parameter;
    NSString *_scheme;
    _Bool _bIsShowLaunchFailToast;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)dealloc;
- (void)handleJSEvent:(id)arg1;
- (void)onCheckResponse:(id)arg1;
- (void)resetCacheParam;
- (void)sendReqLaunchAppWithShowType:(unsigned long long)arg1;

@end

