//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WAMainFrameTaskBarViewDelegate.h"
#import "WAMainFrameTaskItemMgrExt.h"

@class MMUIViewController, NSMutableArray, NSString, WAReportMainFrameTaskBarActionItem;

@interface WAMainFrameTaskBarLogic : MMObject <WAMainFrameTaskItemMgrExt, WAMainFrameTaskBarViewDelegate>
{
    _Bool _isDraggingVisible;
    _Bool _isPullingWhyDragMe;
    unsigned int _openTime;
    id <WAMainFrameTaskBarLogicDelegate> _delegate;
    NSMutableArray *_arrTaskItem;
    MMUIViewController *_containerVC;
    WAReportMainFrameTaskBarActionItem *_actionItem;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WAReportMainFrameTaskBarActionItem *actionItem; // @synthesize actionItem=_actionItem;
@property(retain, nonatomic) NSMutableArray *arrTaskItem; // @synthesize arrTaskItem=_arrTaskItem;
- (void)closeRunningTaskIfHaveByUsername:(id)arg1 debugType:(unsigned int)arg2;
@property(nonatomic) __weak MMUIViewController *containerVC; // @synthesize containerVC=_containerVC;
- (void)dealloc;
@property(nonatomic) __weak id <WAMainFrameTaskBarLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void)endDragToVisible;
- (void)endPullWhyDragMe;
- (id)init;
- (void)initData;
@property(nonatomic) _Bool isDraggingVisible; // @synthesize isDraggingVisible=_isDraggingVisible;
@property(nonatomic) _Bool isPullingWhyDragMe; // @synthesize isPullingWhyDragMe=_isPullingWhyDragMe;
- (_Bool)isShouldShowTaskBarView;
- (_Bool)isSupportWeapp;
- (void)loadTaskItemListWithCount:(unsigned int)arg1;
- (void)onMainFrameTaskItemUpdated;
@property(nonatomic) unsigned int openTime; // @synthesize openTime=_openTime;
- (void)reloadTaskItems;
- (unsigned long long)removeTaskBarItemByUsername:(id)arg1 debugType:(unsigned int)arg2;
- (void)reportVisitAction;
- (void)startDragToVisible;
- (void)startPullWhyDragMe;
- (void)taskBarDidHideWithScene:(unsigned long long)arg1;
- (void)taskBarDidShow;
- (void)taskBarView:(id)arg1 didSelectTaskItem:(id)arg2;
- (void)taskBarViewDidEndDragging:(id)arg1;
- (void)taskBarViewDidSelectMore:(id)arg1;
- (id)taskItemAtRowIndex:(long long)arg1;
- (void)updateContactsFromScene:(unsigned long long)arg1;
- (void)visibleTick;
- (void)whyDragMeTick;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

