//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WAMainFrameTaskBarActionSheetContext : NSObject
{
    unsigned int _debugMode;
    unsigned int _updateTime;
    unsigned long long _action;
    NSString *_userName;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long action; // @synthesize action=_action;
@property(nonatomic) unsigned int debugMode; // @synthesize debugMode=_debugMode;
@property(nonatomic) unsigned int updateTime; // @synthesize updateTime=_updateTime;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;

@end

