//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class DotLoadingView, NSArray, WAHeaderStackDisplayView;

@interface WAMsgFastBrowserView : MMUIView
{
    DotLoadingView *m_loadingView;
    WAHeaderStackDisplayView *m_headerStackView;
    NSArray *_msgs;
}

- (void).cxx_destruct;
- (id)init;
- (void)initView;
- (id)msgContactLogoUrls;
@property(retain, nonatomic) NSArray *msgs; // @synthesize msgs=_msgs;
- (void)setState:(unsigned long long)arg1;

@end

