//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "MsgNewImgDataLogicDelegate.h"

@class CContact, MsgNewImgDataLogic, NSMutableSet, NSString;

@interface WAMsgBrowserDataLogic : MMObject <MsgNewImgDataLogicDelegate>
{
    _Bool _isDone;
    CContact *_contact;
    id <WAMsgBrowserDataLogicDelegate> _delegate;
    MsgNewImgDataLogic *_dataLogic;
    NSMutableSet *_weappSet;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CContact *contact; // @synthesize contact=_contact;
@property(retain, nonatomic) MsgNewImgDataLogic *dataLogic; // @synthesize dataLogic=_dataLogic;
- (void)dealloc;
@property(nonatomic) __weak id <WAMsgBrowserDataLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void)fetchData;
- (id)init;
@property(nonatomic) _Bool isDone; // @synthesize isDone=_isDone;
- (id)msgArr;
- (void)onMsgNewImgDataLogicLoadOKWithLast:(id)arg1 Next:(id)arg2;
- (_Bool)onMsgNewImgLogicDataMatch:(id)arg1;
@property(retain, nonatomic) NSMutableSet *weappSet; // @synthesize weappSet=_weappSet;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

