//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WAPathUtility : NSObject
{
}

+ (id)WAAppCacheSandboxDir;
+ (id)WAAppCacheSandboxDirWithAppID:(id)arg1;
+ (id)WAAppItemOperationsFilePath;
+ (id)WAAppLibrarySandboxDirWithAppID:(id)arg1;
+ (id)WAAppTaskDBPathWithAppID:(id)arg1;
+ (id)WACacheDir;
+ (id)WACacheFileCleanStatusPath;
+ (id)WACommonMarkPath;
+ (id)WACommonPath;
+ (id)WAConfigDir;
+ (id)WADatabasePath;
+ (id)WADebugFavMarkPath;
+ (id)WADebugNotifyFilePath;
+ (id)WADocumentDir;
+ (id)WAFrameContentCachePathWithAppID:(id)arg1;
+ (id)WAHistoryAppNamesFilePath;
+ (id)WAHistoryAppNamesWithMsgFilePath;
+ (id)WAHomeDir;
+ (id)WAHomeLayoutItemFilePath;
+ (id)WAHomeLayoutOldFilePath;
+ (id)WALibraryDir;
+ (id)WALocationCacheFilePath;
+ (id)WARedDotNotifyFilePath;
+ (id)WASearchH5Dir;
+ (id)WASessionNotifyInfoPath;
+ (id)WAShowOutInfoFilePath;
+ (id)WASnapShotDir;
+ (id)WASnapShotImageFolder;
+ (id)WAStandarizePath:(id)arg1;
+ (id)WATemplateMsgInfoFilePath;
+ (id)WATmpDir;
+ (id)WATopSessionTaskInfoFilePath;
+ (id)WAUpdatedSearchH5ConfigPath;
+ (id)WAUpdatedSearchH5Dir;
+ (id)WAUpdatedSearchH5Path;
+ (id)WAWindowConfigCachePathWithAppID:(id)arg1;

@end

