//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WAPackagePredownloadInfo : NSObject
{
    unsigned int _version;
    NSString *_userName;
    NSString *_appId;
    NSString *_packageMd5;
    NSString *_contactResponseString;
    NSString *_launchResponseString;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSString *contactResponseString; // @synthesize contactResponseString=_contactResponseString;
- (id)description;
@property(retain, nonatomic) NSString *launchResponseString; // @synthesize launchResponseString=_launchResponseString;
@property(retain, nonatomic) NSString *packageMd5; // @synthesize packageMd5=_packageMd5;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(nonatomic) unsigned int version; // @synthesize version=_version;

@end

