//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class MMUIButton, MMUILabel, NSString, UIActivityIndicatorView, UIImageView, UILongPressGestureRecognizer, UIView, WAPopOverTaskBarlogic, WAPopOverView, WAWebViewController;

@interface WAWebViewMutiFuncMenuView : MMUIView
{
    NSString *_normalLastNavTitle;
    MMUILabel *_normalTitleView;
    _Bool _isActivityIndicatorAnimating;
    UIActivityIndicatorView *_activityIndicatorView;
    MMUIButton *_returnButton;
    UIView *_menuView;
    MMUIButton *_menuMoreButton;
    MMUIButton *_menuExitButton;
    _Bool _isMenuHidden;
    MMUIButton *_menuStateButton;
    UIImageView *_menuIconView;
    UILongPressGestureRecognizer *_moreLongPressRecognizer;
    _Bool _isTrigerMoreLongPress;
    UILongPressGestureRecognizer *_longPressRecognizer;
    WAPopOverTaskBarlogic *_popOverLogic;
    WAPopOverView *_popOverView;
    _Bool _canShowShare;
    int _navMode;
    id <WAWebViewMutiFuncMenuViewDelegate> _delegate;
    WAWebViewController *_webview;
    long long _contentMode;
    long long _menuState;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool canShowShare; // @synthesize canShowShare=_canShowShare;
- (void)changeMenuStateToLocation;
- (void)changeMenuStateToNormal;
- (void)changeMenuStateToRecordingVideo;
- (void)changeMenuStateToRecordingVoice;
@property(nonatomic) long long contentMode; // @synthesize contentMode=_contentMode;
- (id)copyMenuView;
@property(nonatomic) __weak id <WAWebViewMutiFuncMenuViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)fsmenu_udpateContent;
- (void)fsnormal_layoutContent;
- (void)fsnormal_updateContent;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)isSupportVisualEffect;
- (void)layoutSubviews;
@property(nonatomic) long long menuState; // @synthesize menuState=_menuState;
- (id)menuView;
@property(nonatomic) int navMode; // @synthesize navMode=_navMode;
- (void)onExit;
- (void)onLongPressExitItem:(id)arg1;
- (void)onLongPressMoreItem:(id)arg1;
- (void)onMore;
- (void)onReturn;
- (void)onWebViewDidAppear;
- (id)pluginVideoPlayer;
- (id)pluginWeAppMsg;
- (void)setMenuNavBackgroundColor:(id)arg1;
- (void)setMenuNavTitle:(id)arg1;
- (void)setMenuTitleViewLoading:(_Bool)arg1;
- (void)setMenuViewCapsuleHidden:(_Bool)arg1;
@property(nonatomic) __weak WAWebViewController *webview; // @synthesize webview=_webview;
- (id)stateButton;
- (void)updateMenuViewWithWebContentMode:(long long)arg1 navMode:(int)arg2;

@end

