//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WAWhatsNewStepHandler : NSObject
{
    id <whatsnewViewDelegateEx> _whatsNewDelegate;
}

- (void).cxx_destruct;
- (void)endStep;
- (void)markDismissVerticalAnimation;
@property(nonatomic) __weak id <whatsnewViewDelegateEx> whatsNewDelegate; // @synthesize whatsNewDelegate=_whatsNewDelegate;

@end

