//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCBaseControlLogic.h"

#import "VoicePrintHandlerDelegate.h"
#import "WCAccountErrorHandleLogicDelegate.h"
#import "WCPrivacyPolicyControlLogicDelegate.h"

@class NSString, WCAccountControlData, WCAccountErrorHandleLogic, WCPrivacyPolicyControlLogic;

@interface WCAccountBaseControlLogic : WCBaseControlLogic <WCPrivacyPolicyControlLogicDelegate, VoicePrintHandlerDelegate, WCAccountErrorHandleLogicDelegate>
{
    WCAccountControlData *m_data;
    _Bool m_bDisableDataReport;
    WCAccountErrorHandleLogic *m_errorHandleLogic;
    WCPrivacyPolicyControlLogic *_privacyPolicyLogic;
    CDUnknownBlockType privacyPolicyDoneBlock;
}

- (void).cxx_destruct;
- (void)addTopViewController:(id)arg1;
- (void)delaySetPrivacyPolicyLogicNil;
- (void)disableDataReport;
- (id)initWithData:(id)arg1;
- (_Bool)isFromReg;
- (_Bool)onHandleError:(id)arg1;
- (void)onWCPrivacyPolicyControlLogicClickCancel;
- (void)onWCPrivacyPolicyControlLogicClickClose;
- (void)onWCPrivacyPolicyControlLogicClickDone;
- (void)openMainFrame:(_Bool)arg1 showStyle:(id)arg2;
- (void)removeTopViewController;
- (void)reportEnterView:(id)arg1;
- (void)reportExitView:(id)arg1;
- (void)reportOpenMainView:(id)arg1;
- (void)showPrivacyPolicyWithUrl:(id)arg1 doneBlock:(CDUnknownBlockType)arg2;
- (void)startLoading;
- (void)stopLoading;
- (void)stopLogic;
- (void)vcBecomeFirstResponder;
- (void)vcResignFirstResponder;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

