//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMUIViewController, NSArray, NSString, POIInfo, UIColor, UIView<YYWebViewInterface>, UIViewController, WCCanvasComponent, WCCanvasComponentItem, WCCanvasReportMgr;

@protocol WCCanvasComponentDelegate <NSObject>
- (void)canvasComponent:(WCCanvasComponent *)arg1 willAddViewController:(MMUIViewController *)arg2;
- (void)canvasComponent:(WCCanvasComponent *)arg1 willExistAndJumpUrl:(NSString *)arg2;
- (void)canvasComponent:(WCCanvasComponent *)arg1 willJumpToCanvas:(NSString *)arg2 canvasId:(NSString *)arg3;
- (void)canvasComponent:(WCCanvasComponent *)arg1 willShowViewController:(MMUIViewController *)arg2;
- (_Bool)isSearchCanvas;
- (void)setLoading:(_Bool)arg1;

@optional
- (void)canvasComponent:(WCCanvasComponent *)arg1 shouldForceHideArrowDownImage:(_Bool)arg2;
- (NSString *)getAdUxInfo;
- (UIColor *)getBackGroundColorWhenLoading:(long long)arg1;
- (UIView<YYWebViewInterface> *)getCacheWebviewWithUrl:(NSString *)arg1;
- (void)getCanvasScene:(int *)arg1;
- (UIViewController *)getCurrentViewController;
- (WCCanvasReportMgr *)getReportMgr;
- (NSString *)getWeAppSceneNoteForComponent:(WCCanvasComponent *)arg1;
- (void)hideActionSheet;
- (void)hideDownArrowIcon;
- (_Bool)isCurSectionBlackMoreThanWhite:(long long)arg1;
- (void)jumpStreamVideoForSightComponent:(WCCanvasComponent *)arg1;
- (void)jumpToLocationPage:(POIInfo *)arg1;
- (void)jumpToPhonePage:(NSArray *)arg1;
- (void)onFavProductReturn:(unsigned int)arg1 errMsg:(NSString *)arg2;
- (void)reloadData;
- (_Bool)secionHasShowDownArrow:(long long)arg1;
- (void)showActionSheet:(NSString *)arg1 body:(WCCanvasComponentItem *)arg2 withIcon:(NSString *)arg3 hideHeader:(_Bool)arg4 showCancelAction:(_Bool)arg5;
- (void)tryShowDownArrowAnimate:(long long)arg1;
@end

