//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface WCCardOfflineCodeConfigData : MMObject <WCTTableCoding>
{
    _Bool needInsertShowTimestamp;
    unsigned int lowerBound;
    unsigned int expireTimeInterval;
    unsigned int showExpireInterval;
    unsigned int localUpdateTime;
    NSString *cardId;
    NSString *showTimestampEncryptKey;
}

+ (const struct WCTPropertyList *)AllProperties;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (CDUnknownBlockType)PropertyNamed;
+ (const struct WCTProperty *)cardId;
+ (const struct WCTProperty *)expireTimeInterval;
+ (const struct WCTProperty *)localUpdateTime;
+ (const struct WCTProperty *)lowerBound;
+ (const struct WCTProperty *)needInsertShowTimestamp;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
+ (const struct WCTProperty *)showExpireInterval;
+ (const struct WCTProperty *)showTimestampEncryptKey;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *cardId; // @synthesize cardId;
@property(nonatomic) unsigned int expireTimeInterval; // @synthesize expireTimeInterval;
@property(nonatomic) unsigned int localUpdateTime; // @synthesize localUpdateTime;
@property(nonatomic) unsigned int lowerBound; // @synthesize lowerBound;
@property(nonatomic) _Bool needInsertShowTimestamp; // @synthesize needInsertShowTimestamp;
@property(nonatomic) unsigned int showExpireInterval; // @synthesize showExpireInterval;
@property(retain, nonatomic) NSString *showTimestampEncryptKey; // @synthesize showTimestampEncryptKey;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

