//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "crashReportConnectionDelegate.h"

@class MMCrashReportConnection, NSMutableArray, NSString;

@interface WCDBPerformanceReport : NSObject <crashReportConnectionDelegate>
{
    MMCrashReportConnection *_connection;
    int _timeInterval;
    int _maxSize;
    NSMutableArray *_transactionContents;
}

+ (id)dirOfReportInfo;
+ (id)pathOfReportInfo;
- (void).cxx_destruct;
- (void)addTransactionContent:(id)arg1;
- (void)appendTransactionContent:(id)arg1;
- (void)clearTransactionContent;
- (id)currentUserName;
- (id)initWithConfig:(id)arg1;
- (void)onUploadCrashCompleted:(_Bool)arg1 CrashWrap:(id)arg2;
- (void)report;
@property(retain, nonatomic) NSMutableArray *transactionContents; // @synthesize transactionContents=_transactionContents;
- (_Bool)shouldReport;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

