//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCDBSyncAnalysis;

@interface WCDBReport : NSObject
{
    struct map<std::__1::pair<int, int>, int, std::__1::less<std::__1::pair<int, int>>, std::__1::allocator<std::__1::pair<const std::__1::pair<int, int>, int>>> _idkeyInfo;
    struct map<int, WCDBCorruptReport *, std::__1::less<int>, std::__1::allocator<std::__1::pair<const int, WCDBCorruptReport *>>> _reports;
    WCDBSyncAnalysis *_syncAnalysis;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)clear;
- (void)clearCorruptNum:(int)arg1;
- (id)init;
- (id)processError:(id)arg1;
- (void)reportCorrupt:(id)arg1;
- (void)reportError:(id)arg1;
- (void)reportErrorToIDKey:(id)arg1;
- (void)reportErrorToKV:(id)arg1;

@end

