//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class NSString, WCDBPerformanceReport, WCDBReport;

@interface WCDBManager : MMService <MMService>
{
    NSString *_configPath;
    WCDBReport *_report;
    WCDBPerformanceReport *_performanceReport;
    _Bool _synchronize;
    int _judgeCorruptNum;
    int _integrityDump;
}

+ (id)configPath;
+ (void)initialize;
- (void).cxx_destruct;
- (void)clearCorruptNum:(int)arg1;
- (id)init;
@property int integrityDump; // @synthesize integrityDump=_integrityDump;
@property(readonly) int judgeCorruptNum; // @synthesize judgeCorruptNum=_judgeCorruptNum;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)onServiceReloadData;
@property(readonly) _Bool synchronize; // @synthesize synchronize=_synchronize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

