//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCDBPerformanceReportConfig;

@interface WCDBConfig : NSObject
{
    _Bool shouldDegenarateSync;
    _Bool synchronize;
    int corruptNum;
    int integrityDump;
    WCDBPerformanceReportConfig *performanceReport;
}

+ (id)ABTestConfig;
+ (id)configWithPath:(id)arg1;
+ (void)initialize;
- (void).cxx_destruct;
@property(nonatomic) int corruptNum; // @synthesize corruptNum;
- (id)description;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (id)init;
@property(nonatomic) int integrityDump; // @synthesize integrityDump;
@property(retain, nonatomic) WCDBPerformanceReportConfig *performanceReport; // @synthesize performanceReport;
@property(nonatomic) _Bool shouldDegenarateSync; // @synthesize shouldDegenarateSync;
@property(nonatomic) _Bool synchronize; // @synthesize synchronize;
- (_Bool)writeToFile:(id)arg1;

@end

