//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface WCIdOwner : NSObject <WCTTableCoding>
{
    NSString *_Id;
    NSString *_username;
}

+ (const struct WCTPropertyList *)AllProperties;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTProperty *)Id;
+ (CDUnknownBlockType)PropertyNamed;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
+ (const struct WCTProperty *)username;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *Id; // @synthesize Id=_Id;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

