//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseCgi.h"

@class GetPayMenuRequest;

@interface WCPayWalletPayMenuCgi : WCPayBaseCgi
{
    GetPayMenuRequest *_m_queryRequest;
    id <WCPayWalletPayMenuCgiDelegate> _m_delegate;
}

- (void).cxx_destruct;
- (void)didFailWithError:(id)arg1;
- (void)didGetResponse:(id)arg1;
- (id)init;
@property(nonatomic) __weak id <WCPayWalletPayMenuCgiDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
@property(retain, nonatomic) GetPayMenuRequest *m_queryRequest; // @synthesize m_queryRequest=_m_queryRequest;
- (void)startRequest;

@end

