//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "WCPayLQTCloseFundAccountCgiDelegate.h"
#import "WCPayLQTDetailViewControllerDelegate.h"
#import "WCPayLQTMoneyControlLogicDelegate.h"
#import "WCPayLQTQryUserFundDetailCgiDelegate.h"
#import "WCPayPayPwdViewControllerDelegate.h"

@class NSString, WCPayLQTCloseFundAccountCgi, WCPayLQTMoneyControlLogic, WCPayLQTQryUserFundDetailCgi;

@interface WCPayLQTDetailControlLogic : WCPayControlLogic <WCPayLQTDetailViewControllerDelegate, WCPayLQTQryUserFundDetailCgiDelegate, WCPayLQTCloseFundAccountCgiDelegate, WCPayPayPwdViewControllerDelegate, WCPayLQTMoneyControlLogicDelegate>
{
    id <WCPayLQTDetailControlLogicDelegate> _logicDelegate;
    WCPayLQTQryUserFundDetailCgi *_qryDetailCgi;
    WCPayLQTCloseFundAccountCgi *_closeFundCgi;
    WCPayLQTMoneyControlLogic *_lqtMoneyControlLogic;
    unsigned long long _fromScene;
}

- (void).cxx_destruct;
- (void)OnVerifyPayPassword:(id)arg1;
- (void)PayPwdBack;
- (void)PayPwdRightActionBack;
- (void)VerifyPayPwdNext:(id)arg1;
@property(retain, nonatomic) WCPayLQTCloseFundAccountCgi *closeFundCgi; // @synthesize closeFundCgi=_closeFundCgi;
- (void)dealloc;
- (void)delayDismissViewControllerOnCloseAccount;
@property(nonatomic) unsigned long long fromScene; // @synthesize fromScene=_fromScene;
- (id)initWithFromScene:(unsigned long long)arg1 controlData:(id)arg2;
@property(nonatomic) __weak id <WCPayLQTDetailControlLogicDelegate> logicDelegate; // @synthesize logicDelegate=_logicDelegate;
@property(retain, nonatomic) WCPayLQTMoneyControlLogic *lqtMoneyControlLogic; // @synthesize lqtMoneyControlLogic=_lqtMoneyControlLogic;
- (void)onDetailViewControllerBack;
- (void)onDetailViewControllerFetchBtnClick;
- (void)onDetailViewControllerNeedUpdateDataFromSvr;
- (void)onDetailViewControllerSaveBtnClick;
- (void)onDetailViewControllerUnBindBtnClick;
- (void)onGetLQTCloseFundAccountResp:(id)arg1;
- (void)onGetLQTQryUserFundDetailResp:(id)arg1;
- (void)onLQTMoneyControlLogicNeedToRefreshBalanceDetail;
- (void)onLQTMoneyControlLogicNeedToRefreshLQTDetail;
- (void)onLQTMoneyControlLogicStop;
@property(retain, nonatomic) WCPayLQTQryUserFundDetailCgi *qryDetailCgi; // @synthesize qryDetailCgi=_qryDetailCgi;
- (void)queryUserLQTDetailFromSvrShouldLoading:(_Bool)arg1;
- (void)sendCloseFundAccountRequestWithPwdString:(id)arg1;
- (void)startLQTMoneyControlLogicWithMoneyScece:(unsigned long long)arg1;
- (void)startLogic;
- (void)stopLogic;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

