//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "ILinkEventExt.h"
#import "MMWebViewDelegate.h"
#import "WCActionSheetDelegate.h"
#import "WCPayNoticeBannerDelegate.h"

@class NSDictionary, NSString, RichTextView, UIImageView, WCActionSheet;

@interface WCPayBalanceDetailViewController : WCPayBaseViewController <WCPayNoticeBannerDelegate, MMWebViewDelegate, WCActionSheetDelegate, ILinkEventExt>
{
    WCActionSheet *m_actionSheet;
    id <WCPayBalanceDetailViewControllerDelegate> m_delegate;
    RichTextView *richTextView;
    _Bool m_bDidPoped;
    NSDictionary *m_dicBanners;
    UIImageView *_reddotForLqt;
}

- (void).cxx_destruct;
- (id)GetMainCardHeaderView;
- (void)OnLeftBarButtonDone;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)addQuestionEntrance;
- (void)banner:(id)arg1 clickWithUrl:(id)arg2;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (id)getHeaderView:(id)arg1;
- (id)init;
- (void)initNavigationBar;
- (_Bool)isShowLCTEntry;
- (_Bool)isShowLQTEntry;
- (void)lqtEntryClick;
- (void)onLCTBtnClick:(id)arg1;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onOperate;
- (void)onRealnameBtnClick:(id)arg1;
- (void)onRightBarButtonClick;
- (void)onWalletBtnClick:(id)arg1;
- (void)onWatchBalanceList;
@property(retain, nonatomic) UIImageView *reddotForLqt; // @synthesize reddotForLqt=_reddotForLqt;
- (void)refreshViewWithData:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidLoad;
- (void)webViewReturn:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

