//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSString;

@interface WCPayLQTEnteranceInfo : NSObject <PBCoding>
{
    unsigned int lqt_state;
    NSString *lct_wording;
    NSString *lct_url;
}

+ (id)getLocalLQTEnteranceInfo;
+ (void)initialize;
+ (_Bool)saveLQTEnteranceInfo:(id)arg1;
- (void).cxx_destruct;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
@property(retain, nonatomic) NSString *lct_url; // @synthesize lct_url;
@property(retain, nonatomic) NSString *lct_wording; // @synthesize lct_wording;
@property(nonatomic) unsigned int lqt_state; // @synthesize lqt_state;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

