//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "ILinkEventExt.h"
#import "IdleTimerUtilExt.h"
#import "WCActionSheetDelegate.h"
#import "WCPayFacingQRCodeImageViewDelegate.h"
#import "WCPayNoticeBannerDelegate.h"

@class MMUILabel, NSMutableArray, NSString, RichTextView, UIButton, UIColor, UIImage, UIImageView, UIView, WCPayBannerNotice, WCPayFacingQRCodeImageView, WCUIAlertView;

@interface WCPayFacingReceiveQRCodeViewController : WCPayBaseViewController <IdleTimerUtilExt, WCPayNoticeBannerDelegate, ILinkEventExt, WCActionSheetDelegate, WCPayFacingQRCodeImageViewDelegate>
{
    UIButton *m_footerButton;
    id <WCPayFacingReceiveQRCodeViewControllerDelegate> m_delegate;
    double _oldBrightness;
    UIView *m_oTotalMoneyView;
    NSMutableArray *m_arrPayerInfoView;
    NSMutableArray *m_arrAnimationedMessageStruct;
    UIImage *m_oQRCodeImage;
    WCPayFacingQRCodeImageView *imageQRCodeBackgroundView;
    RichTextView *balanceRichTextView;
    UIView *m_oTotalMoneyBottomLine;
    NSMutableArray *m_arrPayerBottomLine;
    _Bool bDidBePoed;
    _Bool qrcodeIsAnimated;
    UIButton *toBalanceBtn;
    UIColor *originalBarTintColor;
    double introViewHeight;
    double bannerHeight;
    _Bool _bNeedRemoveReddotFromOtherView;
    WCUIAlertView *_screenShotAlert;
    WCPayBannerNotice *_m_bannerNotice;
    UIImageView *_detailReddotImgView;
    MMUILabel *_detailSubLabel;
}

- (void).cxx_destruct;
- (void)EndReceivedMoneyAnimation:(id)arg1;
- (void)OnLeftBarButtonDone;
- (void)OnWCPayFacingQRCodeImageViewSaveButtonDone;
- (void)RemoveMessageStructAndShowedMoney:(id)arg1;
- (void)ShowPayerStartedPayMoneyAnimation:(id)arg1 OnlyChangedOldCell:(_Bool)arg2;
- (void)ShowReceivedMoneyAnimation:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(nonatomic) _Bool bNeedRemoveReddotFromOtherView; // @synthesize bNeedRemoveReddotFromOtherView=_bNeedRemoveReddotFromOtherView;
- (void)banner:(id)arg1 clickWithUrl:(id)arg2;
- (void)dealloc;
@property(retain, nonatomic) UIImageView *detailReddotImgView; // @synthesize detailReddotImgView=_detailReddotImgView;
@property(retain, nonatomic) MMUILabel *detailSubLabel; // @synthesize detailSubLabel=_detailSubLabel;
- (id)genDetailEnteranceViewWithNeedBottomCorner:(_Bool)arg1;
- (id)getActionBarView;
- (id)getBizF2FHeadImageViewWithImageSize:(struct CGSize)arg1;
- (id)getDisplayNameInfo;
- (id)getDisplayTruthNameInfo;
- (id)getLocalSaveAlbumImageViewV2;
- (id)getNewSaveAlbumImageView;
- (id)getNoticeBanner;
- (id)getSaveAlbumImageView;
@property(retain, nonatomic) WCPayFacingQRCodeImageView *imageQRCodeBackgroundView; // @synthesize imageQRCodeBackgroundView;
- (id)init;
- (void)initHeaderView;
- (void)initNavigationBar;
- (void)insertNewView:(id)arg1;
@property(retain, nonatomic) WCPayBannerNotice *m_bannerNotice; // @synthesize m_bannerNotice=_m_bannerNotice;
- (void)onClickToReceiveDetailButton;
- (void)onIdleTimerUtilVoipQuit;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onRightBarButtonClick;
- (void)refreshViewWithData:(id)arg1;
- (void)reloadTableView;
- (void)reportLocation;
- (void)saveQRCodeImageButtonPress;
- (void)saveReceiveCodeImgToAlbumFromAlert;
@property(retain, nonatomic) WCUIAlertView *screenShotAlert; // @synthesize screenShotAlert=_screenShotAlert;
- (void)setDelegate:(id)arg1;
- (void)showActionList;
- (void)showOpenSystemPushSoundTips;
- (void)showSetPushSoundResultSuccess:(_Bool)arg1 soundStatus:(_Bool)arg2;
- (_Bool)useTransparentNavibar;
- (void)userDidTakeScreenshot:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidBeDismissed:(_Bool)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidBePresented:(_Bool)arg1;
- (void)viewDidBePushed:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

