//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "WCPayFillCardInfoViewControllerDelegate.h"
#import "WCPayFillCardNumberViewControllerDelegate.h"
#import "WCPayPayPwdViewControllerDelegate.h"
#import "WCPayTenpayImportCardInfoViewControllerDelegate.h"
#import "WCPayVerifyPayCardViewControllerDelegate.h"

@class JSEvent, NSString, WCBaseControlLogic, WCPayBindCardSuccessResponse, WCPaySetUserExInfoCgi, WCRedEnvelopesControlData;

@interface WCPayAddPayCardLogic : WCPayControlLogic <WCPayFillCardInfoViewControllerDelegate, WCPayFillCardNumberViewControllerDelegate, WCPayPayPwdViewControllerDelegate, WCPayVerifyPayCardViewControllerDelegate, WCPayTenpayImportCardInfoViewControllerDelegate>
{
    int m_uiLogicFinishedStatus;
    int m_uiWCPayAddPayCardLogicScene;
    JSEvent *m_jsEvent;
    NSString *m_nsAddPayCardToken;
    WCRedEnvelopesControlData *m_redEnvelopesData;
    WCBaseControlLogic *_fromControlLogic;
    id <WCPayAddPayCardDelegate> _payCardDelegate;
    WCPaySetUserExInfoCgi *_setUserExInfoCgi;
    WCPayBindCardSuccessResponse *_m_bindCardSuccessResponse;
}

- (void).cxx_destruct;
- (void)EndWCPayAddPayCardLogic;
- (void)EndWCPayAddPayCardLogic:(id)arg1;
- (void)EndWCPayAddPayCardLogic:(id)arg1 withDelay:(_Bool)arg2;
- (void)FillCardInfoCancel;
- (void)FillCardInfoNext:(id)arg1;
- (void)FillCardInfoReadAgreement;
- (void)FillCardNumberBackToRefreshCardList;
- (void)FillCardNumberCancel:(_Bool)arg1;
- (void)FillCardNumberConfirmWithImage:(id)arg1 cardNumber:(id)arg2 data:(id)arg3;
- (void)FillCardNumberNext:(id)arg1;
- (_Bool)NeedShowServiceAppInfo;
- (void)OnBindCardVerifyCard:(id)arg1 Error:(id)arg2;
- (void)OnBindCardVerifySMS:(id)arg1 Error:(id)arg2 repsonse:(id)arg3;
- (void)OnCheckWCPayJsApiRequest:(id)arg1 Error:(id)arg2;
- (void)OnGetBindQueryInfo:(id)arg1 Error:(id)arg2;
- (void)OnGetBindingCardBin:(id)arg1 AvailableBank:(id)arg2 userExInfoResponse:(id)arg3 Error:(id)arg4;
- (void)OnHandleVerifiedSMSString:(id)arg1;
- (void)OnSetWCPayPasswordInBind:(id)arg1 repsonse:(id)arg2;
- (void)OnTenpayImportBindQuery:(id)arg1 AppInfo:(id)arg2 UsrVerifiedInfo:(id)arg3 Error:(id)arg4;
- (void)OnVerifyPayPassword:(id)arg1;
- (void)PayPwdBack;
- (void)PayPwdRightActionBack;
- (void)SetPayPwdNext:(id)arg1;
- (void)VerifyPayCardAgain:(id)arg1;
- (void)VerifyPayCardBack;
- (void)VerifyPayCardNext:(id)arg1;
- (void)VerifyPayPwdNext:(id)arg1;
- (void)WCPayTenpayImportCardInfoViewControllerCancel;
- (void)WCPayTenpayImportCardInfoViewControllerNext;
- (void)WCPayTenpayImportCardInfoViewControllerReadAgreement;
- (void)dealloc;
@property(retain, nonatomic) WCBaseControlLogic *fromControlLogic; // @synthesize fromControlLogic=_fromControlLogic;
- (id)getWCPayBindInfo:(id)arg1;
- (id)initWithData:(id)arg1;
- (id)initWithJSEvent:(id)arg1;
- (id)initWithRedEnvelopesData:(id)arg1;
- (void)jumpSuccessViewController;
@property(retain, nonatomic) WCPayBindCardSuccessResponse *m_bindCardSuccessResponse; // @synthesize m_bindCardSuccessResponse=_m_bindCardSuccessResponse;
@property(nonatomic) int m_uiWCPayAddPayCardLogicScene; // @synthesize m_uiWCPayAddPayCardLogicScene;
- (void)onErrorAlertViewDismiss:(id)arg1;
- (void)onErrorAlertViewStopLogic:(id)arg1;
- (void)onWCPayBindCardSuccessViewControllerClickDone;
- (id)onWCPayBindCardSuccessViewControllerRequestResponse;
@property(nonatomic) __weak id <WCPayAddPayCardDelegate> payCardDelegate; // @synthesize payCardDelegate=_payCardDelegate;
@property(retain, nonatomic) WCPaySetUserExInfoCgi *setUserExInfoCgi; // @synthesize setUserExInfoCgi=_setUserExInfoCgi;
- (void)showGiveUpLogicAlert;
- (void)startAddCardLogic;
- (void)startLogic;
- (void)startTenpayImportCardLogic;
- (void)stopLogic;
- (void)stopLogicToMyPayCardView;
- (void)stopLogicToRefreshPayCardList;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

