//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

@class MMUILabel, UIButton, UIScrollView, WCPayWebImageView;

@interface WCPayBizF2FPaidSuccViewController : WCPayBaseViewController
{
    _Bool _shouldQryActivityStatus;
    id <WCPayBizF2FPaidSuccViewControllerDelegate> _delegate;
    UIScrollView *_contentView;
    WCPayWebImageView *_activityLogoImgView;
    MMUILabel *_activityTitleLabel;
    MMUILabel *_activityContentLabel;
    UIButton *_activityBtn;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *activityBtn; // @synthesize activityBtn=_activityBtn;
- (void)activityBtnClick;
@property(retain, nonatomic) MMUILabel *activityContentLabel; // @synthesize activityContentLabel=_activityContentLabel;
@property(retain, nonatomic) WCPayWebImageView *activityLogoImgView; // @synthesize activityLogoImgView=_activityLogoImgView;
@property(retain, nonatomic) MMUILabel *activityTitleLabel; // @synthesize activityTitleLabel=_activityTitleLabel;
@property(retain, nonatomic) UIScrollView *contentView; // @synthesize contentView=_contentView;
- (void)dealloc;
@property(nonatomic) __weak id <WCPayBizF2FPaidSuccViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)doneBtnClick;
- (id)genActivityInfoView;
- (id)genGreenButton;
- (void)qryActivityStatusIfNeed;
- (void)refreshActivityContent;
@property(nonatomic) _Bool shouldQryActivityStatus; // @synthesize shouldQryActivityStatus=_shouldQryActivityStatus;
- (void)setupContentView;
- (_Bool)useTransparentNavibar;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

@end

