//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WCPayECardFillCardInfoViewController;

@protocol WCPayECardFillCardInfoViewControllerDelegate <NSObject>
- (void)fillCardInfoVC:(WCPayECardFillCardInfoViewController *)arg1 didFilledWithCardNumber:(NSString *)arg2 phoneNumber:(NSString *)arg3;
@end

