//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

@interface WCPayECardBankCardListViewController : WCPayBaseViewController
{
    id <WCPayECardBankCardListViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <WCPayECardBankCardListViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)makeBankCell:(id)arg1 cellInfo:(id)arg2;
- (void)makeBankInfoCell:(id)arg1 bankInfo:(id)arg2;
- (void)makeSelectNewCardCell:(id)arg1;
- (void)makeSelectNewCardToVerifyCell:(id)arg1;
- (void)reloadTableView;
- (void)selectBankInfo:(id)arg1;
- (void)selectVerifyNewCard;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

