//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPaySynthesizeSpeechMsg.h"

@interface WCPayF2FSpeechMsg : WCPaySynthesizeSpeechMsg
{
}

- (id)frontPartSoundPath;
- (unsigned int)getCgiCmd;
- (id)getVoiceRequest;
- (_Bool)isSwitchOpen;
- (void)reportCgiCostTime:(unsigned int)arg1;
- (void)reportIdKeyGetVoiceReq;
- (void)reportIdKeyGetVoiceReqCgiError;
- (void)reportIdKeyGetVoiceReqLocalNetWorkError;
- (void)reportIdKeyGetVoiceReqSuccess;
- (void)reportIdKeyPlaySoundFailed;
- (void)reportIdKeyPlaySoundSuccess;
- (void)reportKVForegroundPlaySoundSuccess;
- (void)reportKVPlaySoundFail;
- (void)reportKVPushSuccess;
- (_Bool)setVoiceResponse:(id)arg1;
- (id)soundNameOfSwitchClose;
- (id)soundNameOfSwitchOpen;

@end

