//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseCgi.h"

@class NSString;

@interface WCPayLQTPurchaseFundCgi : WCPayBaseCgi
{
    unsigned int _fee;
    NSString *_fundCode;
    id <WCPayLQTPurchaseFundCgiDelegate> _cgiDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <WCPayLQTPurchaseFundCgiDelegate> cgiDelegate; // @synthesize cgiDelegate=_cgiDelegate;
- (void)didFailWithError:(id)arg1;
- (void)didGetResponse:(id)arg1;
@property(nonatomic) unsigned int fee; // @synthesize fee=_fee;
@property(retain, nonatomic) NSString *fundCode; // @synthesize fundCode=_fundCode;
- (id)initWithDelegate:(id)arg1;
- (void)startSendRequest;

@end

