//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "CSettingExt.h"
#import "MMWebViewDelegate.h"
#import "SetWCPayWebLogicStateExt.h"
#import "WCPayGetTransferWordingCgiDelegate.h"
#import "WCPayLogicMgrExt.h"

@class GetTransferWordingResponse, MMBadgeView, MMTableViewCellInfo, NSDictionary, NSString, WCPayGetTransferWordingCgi;

@interface WCPayPwdViewController : WCPayBaseViewController <CSettingExt, WCPayGetTransferWordingCgiDelegate, MMWebViewDelegate, WCPayLogicMgrExt, SetWCPayWebLogicStateExt>
{
    id <WCPayPwdViewControllerDelegate> m_delegate;
    _Bool _isDeductShowNew;
    MMTableViewCellInfo *_touchIDSwitchCellInfo;
    MMBadgeView *_touchIDSwithBadgeView;
    MMBadgeView *_autoDeductBadgeView;
    NSDictionary *_payManageData;
    MMTableViewCellInfo *_payManageCellInfo;
    WCPayGetTransferWordingCgi *_wordingCgi;
    GetTransferWordingResponse *_wordingResponse;
}

- (void).cxx_destruct;
- (void)OnBack;
- (void)OnGetBindQueryInfo:(id)arg1 Error:(id)arg2;
@property(retain, nonatomic) MMBadgeView *autoDeductBadgeView; // @synthesize autoDeductBadgeView=_autoDeductBadgeView;
- (void)dealloc;
- (id)delayDurationDesc;
- (void)gotoPayManage:(id)arg1;
- (id)init;
- (void)initCellView;
- (void)initPayManageDataFromCacheOrNetwork;
@property(nonatomic) _Bool isDeductShowNew; // @synthesize isDeductShowNew=_isDeductShowNew;
@property(nonatomic) __weak id <WCPayPwdViewControllerDelegate> m_delegate; // @synthesize m_delegate;
- (void)makeRealnameCell:(id)arg1 CellInfo:(id)arg2;
- (void)onChangeDelayTransferDuration;
- (void)onModifyPwd;
- (void)onRealname;
- (void)onRealnameVerifySuccess;
- (void)onResetPwd;
- (void)onSettingChanged:(int)arg1;
- (void)onSimpleUserSetPwd;
- (void)onTouchIDSwitchChanged:(id)arg1;
@property(retain, nonatomic) MMTableViewCellInfo *payManageCellInfo; // @synthesize payManageCellInfo=_payManageCellInfo;
@property(retain, nonatomic) NSDictionary *payManageData; // @synthesize payManageData=_payManageData;
- (void)reloadTable;
- (void)reloadTableFromCache;
- (void)requestWording;
@property(retain, nonatomic) MMTableViewCellInfo *touchIDSwitchCellInfo; // @synthesize touchIDSwitchCellInfo=_touchIDSwitchCellInfo;
- (void)setTouchIDSwitchValue:(_Bool)arg1;
@property(retain, nonatomic) MMBadgeView *touchIDSwithBadgeView; // @synthesize touchIDSwithBadgeView=_touchIDSwithBadgeView;
- (void)setWCPayWebLogicStateJsapi:(id)arg1 didGetInfo:(id)arg2;
@property(retain, nonatomic) WCPayGetTransferWordingCgi *wordingCgi; // @synthesize wordingCgi=_wordingCgi;
@property(retain, nonatomic) GetTransferWordingResponse *wordingResponse; // @synthesize wordingResponse=_wordingResponse;
- (void)showNewForCellIfNeed:(id)arg1;
- (void)showNewForDeductCellIfNeeded;
- (void)unregisterWCPay;
- (void)updatePayManageData;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidBePushed:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)wcpayGetTransferWordingCgi:(id)arg1 didGetResponse:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

