//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "MMTipsViewControllerDelegate.h"
#import "MMWebViewDelegate.h"
#import "WCPrivacyPolicyToolBarViewDelegate.h"

@class MMUIViewController, MMUIWindow, MMWebViewController, NSString, NSURL, WCPrivacyPolicyToolBarView;

@interface WCPrivacyPolicyControlLogic : MMObject <MMWebViewDelegate, WCPrivacyPolicyToolBarViewDelegate, MMTipsViewControllerDelegate>
{
    MMUIWindow *_window;
    MMUIViewController *_rootVC;
    MMWebViewController *_webviewVC;
    NSURL *_url;
    WCPrivacyPolicyToolBarView *_toolBar;
    _Bool _bFromReg;
    id <WCPrivacyPolicyControlLogicDelegate> _delegate;
    NSString *_webviewUrl;
    NSString *_guidanceContent;
    NSString *_doublecheckContent;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool bFromReg; // @synthesize bFromReg=_bFromReg;
- (_Bool)checkData;
- (void)dealloc;
@property(nonatomic) __weak id <WCPrivacyPolicyControlLogicDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *doublecheckContent; // @synthesize doublecheckContent=_doublecheckContent;
@property(retain, nonatomic) NSString *guidanceContent; // @synthesize guidanceContent=_guidanceContent;
- (void)onClickTipsBtn:(id)arg1 Index:(long long)arg2 withText:(id)arg3 withTipsVC:(id)arg4;
- (void)onWCPrivacyPolicyToolBarViewClickCancel;
- (void)onWCPrivacyPolicyToolBarViewClickDone;
- (void)onWebViewDidFinishLoad:(id)arg1;
@property(retain, nonatomic) NSString *webviewUrl; // @synthesize webviewUrl=_webviewUrl;
- (void)showPrivacyPolicyView;
- (void)startLogic;
- (void)webViewReturn:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

