//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface WCSUITextFieldCheck : MMObject
{
    unsigned long long _startTimeStamp;
    unsigned long long _endTimeStamp;
    unsigned long long _editCnt;
    struct list<unsigned long long, std::__1::allocator<unsigned long long>> _lstTimeStamp;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
- (id)getData;
- (id)init;
- (void)onBeginEdit:(id)arg1;
- (void)onEditChange:(id)arg1;
- (void)onEndEdit:(id)arg1;
- (void)printResult;

@end

