//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCUserComment;

@interface WCUserCommentUICache : NSObject
{
    WCUserComment *m_userComment;
    map_104bc404 m_contentHeight;
    map_96d7b27b m_userCommentLayoutStyles;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (map_104bc404 *)contentHeight;
- (void)dealloc;
- (_Bool)isEmpty;
@property(retain, nonatomic) WCUserComment *userComment; // @synthesize userComment=m_userComment;
- (map_96d7b27b *)userCommentLayoutStyles;

@end

