//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VideoStreamDownloadLogic.h"

#import "WCDownloadVideoCDNMgrExt.h"

@class NSString, VideoStreamKVReportLogic, WCMediaItem;

@interface WCVideoStreamDownloadLogic : VideoStreamDownloadLogic <WCDownloadVideoCDNMgrExt>
{
    WCMediaItem *m_oWCMediaItem;
    VideoStreamKVReportLogic *m_oKVReportLogic;
}

- (void).cxx_destruct;
- (void)OnCdnDownloadSuccess:(id)arg1;
- (void)OnCdnDownloadToEnd:(id)arg1;
- (void)OnDownloadError:(id)arg1;
- (void)OnRecievedFristPartAVData:(id)arg1;
- (void)OnSnsVideoChanged:(id)arg1;
- (void)OnUpdateDownloadProgress:(id)arg1;
- (void)OnVideoCDNDataAvaiable:(id)arg1;
- (void)OnVideoMoovReady:(id)arg1 moovWaitTime:(unsigned int)arg2 Offset:(unsigned int)arg3;
- (void)OnVideoStartDownload:(id)arg1;
- (void)dealloc;
- (void)downloadAllData;
- (id)initWithMediaItem:(id)arg1;
- (_Bool)isVideoCacheDataExistByOffset:(unsigned int)arg1 Length:(unsigned int)arg2;
- (_Bool)isVideoDownloading;
- (id)m_oKVReportLogic;
- (_Bool)requestNetVideoDataByOffset:(unsigned int)arg1 Length:(unsigned int)arg2 DurationSec:(unsigned int)arg3;
- (void)setM_oKVReportLogic:(id)arg1;
- (unsigned long long)startVideoStreamDownload;
- (void)stopVideoStreamDownload;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

