//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMUIViewController, NSMutableArray;

@protocol WNArticleToolViewDelegate <NSObject>
- (MMUIViewController *)getViewController;

@optional
- (_Bool)ifHasReachedSizeLimit;
- (void)insertItems:(NSMutableArray *)arg1;
- (_Bool)isOlLiParagraph;
- (_Bool)isRecording;
- (_Bool)isReminderParagraph;
- (_Bool)isSelectedTextBold;
- (_Bool)isTodoParagraph;
- (_Bool)isUlLiParagraph;
- (void)onParagraphSetOl;
- (void)onParagraphSetUl;
- (void)onShowBasicToolView;
- (void)onShowFullToolView;
- (void)onTextSetBold;
- (void)onToolViewParagraphSetTodo;
@end

