//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@interface WNArticleHeaderView : MMUIView
{
}

- (id)genMomentNoteTimeStringByUInt:(unsigned int)arg1;
- (void)initUI:(id)arg1;
- (id)initWithFavItem:(id)arg1;

@end

