//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WNNoteItemUtilBase : NSObject
{
    id <WNNoteRichEditDelegate> _delegate;
    int _type;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <WNNoteRichEditDelegate> delegate; // @synthesize delegate=_delegate;
- (id)getIconHLName;
- (id)getIconName;
- (id)getIconSelectedName;
- (id)getTitle;
- (void)insertItem:(id)arg1 isUpdate:(_Bool)arg2 isConfigData:(_Bool)arg3;
- (void)onAddItemBegin:(id)arg1;
- (void)onClickItem:(id)arg1;
- (void)onLongClickItem:(id)arg1;
@property(nonatomic) int type; // @synthesize type=_type;

@end

