//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebView.h"

@class UIView;

@interface WNRichEditWebView : UIWebView
{
    UIView *_m_toolView;
}

- (void).cxx_destruct;
- (_Bool)canBecomeFirstResponder;
- (id)inputAccessoryView;
@property(retain, nonatomic) UIView *m_toolView; // @synthesize m_toolView=_m_toolView;

@end

