//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WNVoiceInfo : NSObject
{
    unsigned int voiceDuration;
    unsigned int voiceFmt;
    NSString *voicePath;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) unsigned int voiceDuration; // @synthesize voiceDuration;
@property(nonatomic) unsigned int voiceFmt; // @synthesize voiceFmt;
@property(retain, nonatomic) NSString *voicePath; // @synthesize voicePath;

@end

