//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MMWebSearchViewDelegate.h"

@class MMWebSearchController, NSString, UIView, WCStatTimerHelper;

@interface WSLocalWebViewController : MMUIViewController <MMWebSearchViewDelegate>
{
    UIView *_navBarBkg;
    int _scene;
    MMWebSearchController *_webSearchController;
    WCStatTimerHelper *_pageTimeHelper;
    _Bool m_bShouldForcedRotationToPortrait;
    long long _orientation;
    struct CGRect _videoFrame;
    _Bool _hasInitContainerView;
    _Bool _hasFirstWebviewJsbridgeReady;
    _Bool _hasSendOnUiInitEvent;
    unsigned long long _beginPreloadTime;
    long long _contentInsetAdjustmentBehavior;
    _Bool _shouldForbidCache;
    int _VCType;
    unsigned long long _businessType;
    NSString *_contentTitle;
    id <WSLocalWebViewControllerDelegate> _delegate;
    unsigned long long _enterTime;
}

- (void).cxx_destruct;
@property(nonatomic) int VCType; // @synthesize VCType=_VCType;
@property(nonatomic) unsigned long long businessType; // @synthesize businessType=_businessType;
@property(retain, nonatomic) NSString *contentTitle; // @synthesize contentTitle=_contentTitle;
- (void)dealloc;
@property(nonatomic) __weak id <WSLocalWebViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didFinishLoadWebView:(id)arg1;
- (void)enableFullScreen:(_Bool)arg1 orientation:(long long)arg2 video:(id)arg3;
@property(nonatomic) unsigned long long enterTime; // @synthesize enterTime=_enterTime;
- (id)getTitleLabelWithTitle:(id)arg1;
- (_Bool)hasFirstWebviewJsbridgeReady;
- (void)initNavigationBar;
- (void)initTitleView;
- (void)initView;
- (void)initWebSearchController;
- (id)initWithScene:(int)arg1;
- (void)onJsbridgeReady:(id)arg1;
- (void)onNavigationBackItemClick:(id)arg1;
- (void)onTryForbidCacheVcWhenWebviewCauseError:(id)arg1;
- (void)onUpdateTitleViewWithTitle:(id)arg1;
- (void)onWSLocalWebViewReturn;
- (void)preInitContainerView;
@property(readonly, nonatomic) _Bool shouldForbidCache; // @synthesize shouldForbidCache=_shouldForbidCache;
- (void)startForcedRotation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)tryInitContainerView;
- (void)updateTitleViewWithTitle:(id)arg1;
- (_Bool)useTransparentNavibar;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillBePushed:(_Bool)arg1;
- (void)viewWillPop:(_Bool)arg1;
- (double)webSearchViewPosY;
- (void)willDisappear;
- (void)windowHide:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

