//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WSStreamPlayerView, WSVideoFlowTableViewCell, WSVideoModel;

@protocol WSVideoFlowTableViewCellDelegate <NSObject>

@optional
- (_Bool)canLoadNextWithCurrent:(WSVideoFlowTableViewCell *)arg1;
- (void)enableFullScreen:(_Bool)arg1 orientation:(long long)arg2 cell:(WSVideoFlowTableViewCell *)arg3 video:(WSStreamPlayerView *)arg4;
- (unsigned int)getCachedPlayTimeForVideo:(WSVideoModel *)arg1;
- (void)onClickCellRecommend:(WSVideoModel *)arg1;
- (void)onClickCellSource:(WSVideoModel *)arg1;
- (void)onClickCellTitle:(WSVideoModel *)arg1;
- (void)onClickShare:(WSVideoModel *)arg1;
- (void)onRealBeginPlay:(WSVideoFlowTableViewCell *)arg1 autoPlay:(_Bool)arg2;
- (void)onTapMaskView:(WSVideoFlowTableViewCell *)arg1;
- (WSVideoModel *)onTryPlayNext:(_Bool)arg1 currentVideo:(WSVideoModel *)arg2;
- (_Bool)onVideoPlayEnd:(WSStreamPlayerView *)arg1;
@end

