//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMTableViewCell.h"

#import "WSVideoPlayerViewDelegate.h"

@class MMUILabel, NSString, UIButton, UIView, WSStreamPlayerView, WSVideoModel;

@interface WSVideoFlowTableViewCell : MMTableViewCell <WSVideoPlayerViewDelegate>
{
    UIButton *_sourceLabelButton;
    UIButton *_recommendButton;
    UIButton *_shareButton;
    MMUILabel *_titleLabel;
    MMUILabel *_countLabel;
    UIView *_divLine;
    UIView *_videoMaskView;
    UIView *_videoTopMaskView;
    UIView *_videoBottomMaskView;
    id <WSVideoFlowTableViewCellDelegate> _delegate;
    WSStreamPlayerView *_videoPlayerView;
    WSVideoModel *_videoModel;
}

+ (double)EstimatedCellHeight;
+ (double)HeightForBottomPanel:(id)arg1 maxWidth:(double)arg2;
+ (double)HeightForBottomRecommendPanel:(id)arg1;
+ (double)HeightForDescLabel:(id)arg1 maxWidth:(double)arg2;
+ (double)HeightForVideoModel:(id)arg1 maxWidth:(double)arg2;
+ (double)HeightForVideoPlayerView;
+ (double)OffsetYForVideoPlayerView;
- (void).cxx_destruct;
- (_Bool)canPlayNextVideo;
- (void)dealloc;
@property(nonatomic) __weak id <WSVideoFlowTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)enableFullScreen:(_Bool)arg1 orientation:(long long)arg2 video:(id)arg3;
- (void)forcePlayVideo;
- (id)getPlayCountLabelText;
- (void)initCountLabel;
- (void)initDescLabel;
- (void)initDivLine;
- (void)initMaskView;
- (void)initRecommedButton;
- (void)initShareButton;
- (void)initSourceLabel;
- (void)initView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutCountLabel;
- (void)layoutDescLabel;
- (void)layoutDivLine;
- (void)layoutMaskView;
- (void)layoutRecommendButton;
- (void)layoutShareButton;
- (void)layoutSourceLabel;
- (void)layoutSubviews;
- (void)layoutVideoPlayerView;
- (void)layoutViews;
- (void)onDelayPlayVideo;
- (void)onItemOperate:(id)arg1;
- (void)onOperateShare:(id)arg1;
- (id)onPlayNextVideo:(_Bool)arg1 currentVideo:(id)arg2;
- (void)onShare:(id)arg1;
- (void)onTapMaskView:(id)arg1;
- (void)onTapSurroundings:(id)arg1;
- (void)onTapTitle:(id)arg1;
- (_Bool)onVideoPlayEnd;
- (void)onVideoStateChange:(long long)arg1;
- (void)playVideo;
- (void)playVideoForce:(_Bool)arg1;
- (void)removePlayerView;
- (void)reset;
- (void)resetSurroundMask;
- (void)resumePlayerView:(id)arg1;
- (void)setVideoInfo:(id)arg1;
@property(retain, nonatomic) WSVideoModel *videoModel; // @synthesize videoModel=_videoModel;
- (void)showAsPreparePlay;
- (void)updateVideoThumb;
@property(readonly, nonatomic) WSStreamPlayerView *videoPlayerView; // @synthesize videoPlayerView=_videoPlayerView;
- (void)weakenCell:(_Bool)arg1 animated:(_Bool)arg2;
- (void)weakenSurrounds:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

