//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface WxaPluginSDKInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *pluginSdkAppid; // @dynamic pluginSdkAppid;
@property(retain, nonatomic) NSString *sourceAppid; // @dynamic sourceAppid;

@end

