//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "crashReportConnectionDelegate.h"

@class CrashReportInfo, MMCrashReportConnection, NSObject<OS_dispatch_queue>, NSString;

@interface WXGCrashReportHandler : NSObject <crashReportConnectionDelegate>
{
    MMCrashReportConnection *m_crashReportConnection;
    CrashReportInfo *m_oCrashReportInfo;
    NSObject<OS_dispatch_queue> *m_crashRepoterQueue;
    _Bool m_uploading;
    unsigned long long m_reportType;
}

+ (void)clearCrashData;
+ (void)deleteCrashDataWithReportID:(id)arg1;
+ (id)formCrashReportWrapWithCrashData:(id)arg1;
+ (id)getCrashReportInfoPath;
+ (id)getCurrentDateForCrashReportInfo;
+ (void)initialize;
+ (_Bool)isCrashReportID:(id)arg1;
+ (id)loadPendingCrashReportData;
+ (id)loadPendingCrashReportID;
+ (void)refreshKSCrashReportAppVersion;
+ (void)reportCrashReportCount:(_Bool)arg1 withCrashReportWrap:(id)arg2;
+ (void)reportCrashReportResult:(_Bool)arg1 withCrashReportWrap:(id)arg2;
+ (void)reportId:(int)arg1 key:(int)arg2 andValue:(int)arg3;
+ (void)reportIdKeyList:(vector_ecc2264a)arg1;
+ (void)reportWithID:(int)arg1 ext:(id)arg2 isReportNow:(_Bool)arg3 isKeyLog:(_Bool)arg4;
+ (id)shareCrashReportHandler;
- (void).cxx_destruct;
- (void)dealloc;
- (void)delayReportCrash;
- (void)doWatchExceptionReport;
- (void)enableCrashReportHandler;
- (_Bool)hasCrashReport;
- (id)init;
- (void)loadCrashReportInfo;
- (void)onClientVersionChange;
- (void)onUploadCrashCompleted:(_Bool)arg1 CrashWrap:(id)arg2;
- (void)p_doCrashReport:(unsigned long long)arg1;
- (void)p_tryUpload;
- (void)refreshCrashReportInfo;
- (void)reportCrash;
- (void)reportCrash:(unsigned long long)arg1 WithReportID:(id)arg2;
- (_Bool)reportCrashReportOnSafeMode;
- (void)saveCrashReportInfo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

