//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDateFormatter;

@interface XOGPUImageLogRedirector : NSObject
{
    id <XOGPUImageLogRedirectorDelegate> _delegate;
    NSDateFormatter *_dateFormatter;
}

+ (void)redirectLogWithModule:(id)arg1 fileName:(id)arg2 funcName:(id)arg3 lineNumber:(int)arg4 format:(id)arg5;
+ (id)sharedRedirector;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(nonatomic) __weak id <XOGPUImageLogRedirectorDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
- (void)postLog:(id)arg1 module:(id)arg2 fileName:(id)arg3 funcName:(id)arg4 lineNumber:(int)arg5;

@end

